global:
  resolve_timeout: 5m

route:
  # Default receiver for all alerts
  receiver: 'webhook-receiver'

  # Group alerts by alertname, severity, team, and source names (more readable than IDs)
  group_by: ['alertname', 'severity', 'team', 'source']

  # Wait 10 seconds before sending initial notification
  # Allows for grouping similar alerts together
  group_wait: 10s

  # Wait 30 seconds before sending updates about the same group
  group_interval: 30s

  # Resend notification every 12 hours if alert is still firing
  repeat_interval: 12h

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://webhook-receiver:8080/webhook'
        send_resolved: true
        http_config:
          follow_redirects: true
        max_alerts: 0

inhibit_rules:
  # Inhibit critical alerts if the same alert is already firing at warning level
  # This prevents duplicate notifications for the same issue
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'team', 'source']
