[server]
port = 8125
host = "0.0.0.0"
frontend_url = "http://localhost:5173"  # Development frontend URL, empty in production

[sqlite]
path = "local.db"

[oidc]
provider_url = "http://localhost:5556/dex"
client_id = "logchef"
client_secret = "logchef-secret"
redirect_url = "http://localhost:8125/api/v1/auth/callback"  # Backend callback URL
scopes = ["openid", "email", "profile"]

[auth]
admin_emails = ["admin@example.com"]
session_duration = "8h"
max_concurrent_sessions = 1
