{{- if and .Values.dex.enabled (eq .Values.dex.storage.type "sqlite3") .Values.dex.persistence.enabled (not .Values.dex.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "logchef.dexServiceName" . }}-data
  labels:
    {{- include "logchef.labels" . | nindent 4 }}
    app.kubernetes.io/component: dex
spec:
  accessModes:
    {{- toYaml .Values.dex.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.dex.persistence.size | quote }}
  {{- with .Values.dex.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
