// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCollectionItemStmt, err = db.PrepareContext(ctx, addCollectionItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddCollectionItem: %w", err)
	}
	if q.addCollectionMemberStmt, err = db.PrepareContext(ctx, addCollectionMember); err != nil {
		return nil, fmt.Errorf("error preparing query AddCollectionMember: %w", err)
	}
	if q.addTeamMemberStmt, err = db.PrepareContext(ctx, addTeamMember); err != nil {
		return nil, fmt.Errorf("error preparing query AddTeamMember: %w", err)
	}
	if q.addTeamSourceStmt, err = db.PrepareContext(ctx, addTeamSource); err != nil {
		return nil, fmt.Errorf("error preparing query AddTeamSource: %w", err)
	}
	if q.completeExportJobStmt, err = db.PrepareContext(ctx, completeExportJob); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteExportJob: %w", err)
	}
	if q.countAdminUsersStmt, err = db.PrepareContext(ctx, countAdminUsers); err != nil {
		return nil, fmt.Errorf("error preparing query CountAdminUsers: %w", err)
	}
	if q.countSharedCollectionEditAccessStmt, err = db.PrepareContext(ctx, countSharedCollectionEditAccess); err != nil {
		return nil, fmt.Errorf("error preparing query CountSharedCollectionEditAccess: %w", err)
	}
	if q.countUserSessionsStmt, err = db.PrepareContext(ctx, countUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query CountUserSessions: %w", err)
	}
	if q.createAPITokenStmt, err = db.PrepareContext(ctx, createAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAPIToken: %w", err)
	}
	if q.createAlertStmt, err = db.PrepareContext(ctx, createAlert); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAlert: %w", err)
	}
	if q.createCollectionStmt, err = db.PrepareContext(ctx, createCollection); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCollection: %w", err)
	}
	if q.createDashboardStmt, err = db.PrepareContext(ctx, createDashboard); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDashboard: %w", err)
	}
	if q.createExportJobStmt, err = db.PrepareContext(ctx, createExportJob); err != nil {
		return nil, fmt.Errorf("error preparing query CreateExportJob: %w", err)
	}
	if q.createQueryShareStmt, err = db.PrepareContext(ctx, createQueryShare); err != nil {
		return nil, fmt.Errorf("error preparing query CreateQueryShare: %w", err)
	}
	if q.createSavedQueryStmt, err = db.PrepareContext(ctx, createSavedQuery); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSavedQuery: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createSourceStmt, err = db.PrepareContext(ctx, createSource); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSource: %w", err)
	}
	if q.createTeamStmt, err = db.PrepareContext(ctx, createTeam); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTeam: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteAPITokenStmt, err = db.PrepareContext(ctx, deleteAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAPIToken: %w", err)
	}
	if q.deleteAlertStmt, err = db.PrepareContext(ctx, deleteAlert); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAlert: %w", err)
	}
	if q.deleteCollectionStmt, err = db.PrepareContext(ctx, deleteCollection); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCollection: %w", err)
	}
	if q.deleteDashboardStmt, err = db.PrepareContext(ctx, deleteDashboard); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDashboard: %w", err)
	}
	if q.deleteExpiredExportJobsStmt, err = db.PrepareContext(ctx, deleteExpiredExportJobs); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredExportJobs: %w", err)
	}
	if q.deleteExpiredSessionsStmt, err = db.PrepareContext(ctx, deleteExpiredSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredSessions: %w", err)
	}
	if q.deleteQueryShareStmt, err = db.PrepareContext(ctx, deleteQueryShare); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteQueryShare: %w", err)
	}
	if q.deleteSavedQueryStmt, err = db.PrepareContext(ctx, deleteSavedQuery); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSavedQuery: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSourceStmt, err = db.PrepareContext(ctx, deleteSource); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSource: %w", err)
	}
	if q.deleteSystemSettingStmt, err = db.PrepareContext(ctx, deleteSystemSetting); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSystemSetting: %w", err)
	}
	if q.deleteTeamStmt, err = db.PrepareContext(ctx, deleteTeam); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTeam: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserSessionsStmt, err = db.PrepareContext(ctx, deleteUserSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserSessions: %w", err)
	}
	if q.failExportJobStmt, err = db.PrepareContext(ctx, failExportJob); err != nil {
		return nil, fmt.Errorf("error preparing query FailExportJob: %w", err)
	}
	if q.getAPITokenStmt, err = db.PrepareContext(ctx, getAPIToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetAPIToken: %w", err)
	}
	if q.getAPITokenByHashStmt, err = db.PrepareContext(ctx, getAPITokenByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetAPITokenByHash: %w", err)
	}
	if q.getAlertStmt, err = db.PrepareContext(ctx, getAlert); err != nil {
		return nil, fmt.Errorf("error preparing query GetAlert: %w", err)
	}
	if q.getCollectionStmt, err = db.PrepareContext(ctx, getCollection); err != nil {
		return nil, fmt.Errorf("error preparing query GetCollection: %w", err)
	}
	if q.getCollectionMemberStmt, err = db.PrepareContext(ctx, getCollectionMember); err != nil {
		return nil, fmt.Errorf("error preparing query GetCollectionMember: %w", err)
	}
	if q.getDashboardStmt, err = db.PrepareContext(ctx, getDashboard); err != nil {
		return nil, fmt.Errorf("error preparing query GetDashboard: %w", err)
	}
	if q.getExportJobStmt, err = db.PrepareContext(ctx, getExportJob); err != nil {
		return nil, fmt.Errorf("error preparing query GetExportJob: %w", err)
	}
	if q.getLatestUnresolvedAlertHistoryStmt, err = db.PrepareContext(ctx, getLatestUnresolvedAlertHistory); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestUnresolvedAlertHistory: %w", err)
	}
	if q.getPersonalCollectionStmt, err = db.PrepareContext(ctx, getPersonalCollection); err != nil {
		return nil, fmt.Errorf("error preparing query GetPersonalCollection: %w", err)
	}
	if q.getQueryShareStmt, err = db.PrepareContext(ctx, getQueryShare); err != nil {
		return nil, fmt.Errorf("error preparing query GetQueryShare: %w", err)
	}
	if q.getSavedQueryStmt, err = db.PrepareContext(ctx, getSavedQuery); err != nil {
		return nil, fmt.Errorf("error preparing query GetSavedQuery: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getSourceStmt, err = db.PrepareContext(ctx, getSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetSource: %w", err)
	}
	if q.getSourceByIdentityKeyStmt, err = db.PrepareContext(ctx, getSourceByIdentityKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetSourceByIdentityKey: %w", err)
	}
	if q.getSourceByNameForProvisioningStmt, err = db.PrepareContext(ctx, getSourceByNameForProvisioning); err != nil {
		return nil, fmt.Errorf("error preparing query GetSourceByNameForProvisioning: %w", err)
	}
	if q.getSystemSettingStmt, err = db.PrepareContext(ctx, getSystemSetting); err != nil {
		return nil, fmt.Errorf("error preparing query GetSystemSetting: %w", err)
	}
	if q.getTeamStmt, err = db.PrepareContext(ctx, getTeam); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeam: %w", err)
	}
	if q.getTeamByNameStmt, err = db.PrepareContext(ctx, getTeamByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamByName: %w", err)
	}
	if q.getTeamMemberStmt, err = db.PrepareContext(ctx, getTeamMember); err != nil {
		return nil, fmt.Errorf("error preparing query GetTeamMember: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserPreferencesStmt, err = db.PrepareContext(ctx, getUserPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserPreferences: %w", err)
	}
	if q.getUserTeamForSourceStmt, err = db.PrepareContext(ctx, getUserTeamForSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserTeamForSource: %w", err)
	}
	if q.insertAlertHistoryStmt, err = db.PrepareContext(ctx, insertAlertHistory); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAlertHistory: %w", err)
	}
	if q.isSourceManagedStmt, err = db.PrepareContext(ctx, isSourceManaged); err != nil {
		return nil, fmt.Errorf("error preparing query IsSourceManaged: %w", err)
	}
	if q.isTeamManagedStmt, err = db.PrepareContext(ctx, isTeamManaged); err != nil {
		return nil, fmt.Errorf("error preparing query IsTeamManaged: %w", err)
	}
	if q.isUserManagedStmt, err = db.PrepareContext(ctx, isUserManaged); err != nil {
		return nil, fmt.Errorf("error preparing query IsUserManaged: %w", err)
	}
	if q.listAPITokensForUserStmt, err = db.PrepareContext(ctx, listAPITokensForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListAPITokensForUser: %w", err)
	}
	if q.listAccessibleSourceIDsForUserStmt, err = db.PrepareContext(ctx, listAccessibleSourceIDsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccessibleSourceIDsForUser: %w", err)
	}
	if q.listActiveAlertsDueStmt, err = db.PrepareContext(ctx, listActiveAlertsDue); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveAlertsDue: %w", err)
	}
	if q.listAlertHistoryStmt, err = db.PrepareContext(ctx, listAlertHistory); err != nil {
		return nil, fmt.Errorf("error preparing query ListAlertHistory: %w", err)
	}
	if q.listAlertsBySourceStmt, err = db.PrepareContext(ctx, listAlertsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query ListAlertsBySource: %w", err)
	}
	if q.listAlertsForUserStmt, err = db.PrepareContext(ctx, listAlertsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListAlertsForUser: %w", err)
	}
	if q.listAllSavedQueriesStmt, err = db.PrepareContext(ctx, listAllSavedQueries); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSavedQueries: %w", err)
	}
	if q.listCollectionItemsStmt, err = db.PrepareContext(ctx, listCollectionItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListCollectionItems: %w", err)
	}
	if q.listCollectionMembersStmt, err = db.PrepareContext(ctx, listCollectionMembers); err != nil {
		return nil, fmt.Errorf("error preparing query ListCollectionMembers: %w", err)
	}
	if q.listCollectionsForUserStmt, err = db.PrepareContext(ctx, listCollectionsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListCollectionsForUser: %w", err)
	}
	if q.listDashboardsStmt, err = db.PrepareContext(ctx, listDashboards); err != nil {
		return nil, fmt.Errorf("error preparing query ListDashboards: %w", err)
	}
	if q.listExpiredExportJobPathsStmt, err = db.PrepareContext(ctx, listExpiredExportJobPaths); err != nil {
		return nil, fmt.Errorf("error preparing query ListExpiredExportJobPaths: %w", err)
	}
	if q.listManagedSourcesStmt, err = db.PrepareContext(ctx, listManagedSources); err != nil {
		return nil, fmt.Errorf("error preparing query ListManagedSources: %w", err)
	}
	if q.listManagedTeamsStmt, err = db.PrepareContext(ctx, listManagedTeams); err != nil {
		return nil, fmt.Errorf("error preparing query ListManagedTeams: %w", err)
	}
	if q.listManagedUsersStmt, err = db.PrepareContext(ctx, listManagedUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListManagedUsers: %w", err)
	}
	if q.listSavedQueriesForUserStmt, err = db.PrepareContext(ctx, listSavedQueriesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListSavedQueriesForUser: %w", err)
	}
	if q.listSavedQueriesForUserBySourceStmt, err = db.PrepareContext(ctx, listSavedQueriesForUserBySource); err != nil {
		return nil, fmt.Errorf("error preparing query ListSavedQueriesForUserBySource: %w", err)
	}
	if q.listServiceAccountsStmt, err = db.PrepareContext(ctx, listServiceAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListServiceAccounts: %w", err)
	}
	if q.listSourceTeamsStmt, err = db.PrepareContext(ctx, listSourceTeams); err != nil {
		return nil, fmt.Errorf("error preparing query ListSourceTeams: %w", err)
	}
	if q.listSourcesStmt, err = db.PrepareContext(ctx, listSources); err != nil {
		return nil, fmt.Errorf("error preparing query ListSources: %w", err)
	}
	if q.listSourcesForUserStmt, err = db.PrepareContext(ctx, listSourcesForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListSourcesForUser: %w", err)
	}
	if q.listSystemSettingsStmt, err = db.PrepareContext(ctx, listSystemSettings); err != nil {
		return nil, fmt.Errorf("error preparing query ListSystemSettings: %w", err)
	}
	if q.listSystemSettingsByCategoryStmt, err = db.PrepareContext(ctx, listSystemSettingsByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query ListSystemSettingsByCategory: %w", err)
	}
	if q.listTeamMembersStmt, err = db.PrepareContext(ctx, listTeamMembers); err != nil {
		return nil, fmt.Errorf("error preparing query ListTeamMembers: %w", err)
	}
	if q.listTeamMembersWithDetailsStmt, err = db.PrepareContext(ctx, listTeamMembersWithDetails); err != nil {
		return nil, fmt.Errorf("error preparing query ListTeamMembersWithDetails: %w", err)
	}
	if q.listTeamSourcesStmt, err = db.PrepareContext(ctx, listTeamSources); err != nil {
		return nil, fmt.Errorf("error preparing query ListTeamSources: %w", err)
	}
	if q.listTeamsStmt, err = db.PrepareContext(ctx, listTeams); err != nil {
		return nil, fmt.Errorf("error preparing query ListTeams: %w", err)
	}
	if q.listTeamsForUserStmt, err = db.PrepareContext(ctx, listTeamsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListTeamsForUser: %w", err)
	}
	if q.listUserTeamsStmt, err = db.PrepareContext(ctx, listUserTeams); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserTeams: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.markAlertEvaluatedStmt, err = db.PrepareContext(ctx, markAlertEvaluated); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAlertEvaluated: %w", err)
	}
	if q.markAlertTriggeredStmt, err = db.PrepareContext(ctx, markAlertTriggered); err != nil {
		return nil, fmt.Errorf("error preparing query MarkAlertTriggered: %w", err)
	}
	if q.pruneAlertHistoryStmt, err = db.PrepareContext(ctx, pruneAlertHistory); err != nil {
		return nil, fmt.Errorf("error preparing query PruneAlertHistory: %w", err)
	}
	if q.pruneExpiredQuerySharesStmt, err = db.PrepareContext(ctx, pruneExpiredQueryShares); err != nil {
		return nil, fmt.Errorf("error preparing query PruneExpiredQueryShares: %w", err)
	}
	if q.removeCollectionItemStmt, err = db.PrepareContext(ctx, removeCollectionItem); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveCollectionItem: %w", err)
	}
	if q.removeCollectionMemberStmt, err = db.PrepareContext(ctx, removeCollectionMember); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveCollectionMember: %w", err)
	}
	if q.removeTeamMemberStmt, err = db.PrepareContext(ctx, removeTeamMember); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTeamMember: %w", err)
	}
	if q.removeTeamSourceStmt, err = db.PrepareContext(ctx, removeTeamSource); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTeamSource: %w", err)
	}
	if q.resolveAlertHistoryStmt, err = db.PrepareContext(ctx, resolveAlertHistory); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveAlertHistory: %w", err)
	}
	if q.setSourceManagedStmt, err = db.PrepareContext(ctx, setSourceManaged); err != nil {
		return nil, fmt.Errorf("error preparing query SetSourceManaged: %w", err)
	}
	if q.setTeamManagedStmt, err = db.PrepareContext(ctx, setTeamManaged); err != nil {
		return nil, fmt.Errorf("error preparing query SetTeamManaged: %w", err)
	}
	if q.setUserManagedStmt, err = db.PrepareContext(ctx, setUserManaged); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserManaged: %w", err)
	}
	if q.setUserPasswordHashStmt, err = db.PrepareContext(ctx, setUserPasswordHash); err != nil {
		return nil, fmt.Errorf("error preparing query SetUserPasswordHash: %w", err)
	}
	if q.teamHasSourceStmt, err = db.PrepareContext(ctx, teamHasSource); err != nil {
		return nil, fmt.Errorf("error preparing query TeamHasSource: %w", err)
	}
	if q.touchQueryShareStmt, err = db.PrepareContext(ctx, touchQueryShare); err != nil {
		return nil, fmt.Errorf("error preparing query TouchQueryShare: %w", err)
	}
	if q.updateAPITokenLastUsedStmt, err = db.PrepareContext(ctx, updateAPITokenLastUsed); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAPITokenLastUsed: %w", err)
	}
	if q.updateAlertStmt, err = db.PrepareContext(ctx, updateAlert); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAlert: %w", err)
	}
	if q.updateAlertHistoryPayloadStmt, err = db.PrepareContext(ctx, updateAlertHistoryPayload); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAlertHistoryPayload: %w", err)
	}
	if q.updateCollectionStmt, err = db.PrepareContext(ctx, updateCollection); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCollection: %w", err)
	}
	if q.updateDashboardStmt, err = db.PrepareContext(ctx, updateDashboard); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDashboard: %w", err)
	}
	if q.updateExportJobRunningStmt, err = db.PrepareContext(ctx, updateExportJobRunning); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateExportJobRunning: %w", err)
	}
	if q.updateSavedQueryStmt, err = db.PrepareContext(ctx, updateSavedQuery); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSavedQuery: %w", err)
	}
	if q.updateSourceStmt, err = db.PrepareContext(ctx, updateSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSource: %w", err)
	}
	if q.updateTeamStmt, err = db.PrepareContext(ctx, updateTeam); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTeam: %w", err)
	}
	if q.updateTeamMemberRoleStmt, err = db.PrepareContext(ctx, updateTeamMemberRole); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTeamMemberRole: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.upsertSystemSettingStmt, err = db.PrepareContext(ctx, upsertSystemSetting); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSystemSetting: %w", err)
	}
	if q.upsertUserPreferencesStmt, err = db.PrepareContext(ctx, upsertUserPreferences); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertUserPreferences: %w", err)
	}
	if q.userHasSourceAccessStmt, err = db.PrepareContext(ctx, userHasSourceAccess); err != nil {
		return nil, fmt.Errorf("error preparing query UserHasSourceAccess: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCollectionItemStmt != nil {
		if cerr := q.addCollectionItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCollectionItemStmt: %w", cerr)
		}
	}
	if q.addCollectionMemberStmt != nil {
		if cerr := q.addCollectionMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCollectionMemberStmt: %w", cerr)
		}
	}
	if q.addTeamMemberStmt != nil {
		if cerr := q.addTeamMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTeamMemberStmt: %w", cerr)
		}
	}
	if q.addTeamSourceStmt != nil {
		if cerr := q.addTeamSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTeamSourceStmt: %w", cerr)
		}
	}
	if q.completeExportJobStmt != nil {
		if cerr := q.completeExportJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeExportJobStmt: %w", cerr)
		}
	}
	if q.countAdminUsersStmt != nil {
		if cerr := q.countAdminUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAdminUsersStmt: %w", cerr)
		}
	}
	if q.countSharedCollectionEditAccessStmt != nil {
		if cerr := q.countSharedCollectionEditAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSharedCollectionEditAccessStmt: %w", cerr)
		}
	}
	if q.countUserSessionsStmt != nil {
		if cerr := q.countUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUserSessionsStmt: %w", cerr)
		}
	}
	if q.createAPITokenStmt != nil {
		if cerr := q.createAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAPITokenStmt: %w", cerr)
		}
	}
	if q.createAlertStmt != nil {
		if cerr := q.createAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAlertStmt: %w", cerr)
		}
	}
	if q.createCollectionStmt != nil {
		if cerr := q.createCollectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCollectionStmt: %w", cerr)
		}
	}
	if q.createDashboardStmt != nil {
		if cerr := q.createDashboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDashboardStmt: %w", cerr)
		}
	}
	if q.createExportJobStmt != nil {
		if cerr := q.createExportJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createExportJobStmt: %w", cerr)
		}
	}
	if q.createQueryShareStmt != nil {
		if cerr := q.createQueryShareStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createQueryShareStmt: %w", cerr)
		}
	}
	if q.createSavedQueryStmt != nil {
		if cerr := q.createSavedQueryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSavedQueryStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createSourceStmt != nil {
		if cerr := q.createSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSourceStmt: %w", cerr)
		}
	}
	if q.createTeamStmt != nil {
		if cerr := q.createTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTeamStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteAPITokenStmt != nil {
		if cerr := q.deleteAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAPITokenStmt: %w", cerr)
		}
	}
	if q.deleteAlertStmt != nil {
		if cerr := q.deleteAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAlertStmt: %w", cerr)
		}
	}
	if q.deleteCollectionStmt != nil {
		if cerr := q.deleteCollectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCollectionStmt: %w", cerr)
		}
	}
	if q.deleteDashboardStmt != nil {
		if cerr := q.deleteDashboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDashboardStmt: %w", cerr)
		}
	}
	if q.deleteExpiredExportJobsStmt != nil {
		if cerr := q.deleteExpiredExportJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredExportJobsStmt: %w", cerr)
		}
	}
	if q.deleteExpiredSessionsStmt != nil {
		if cerr := q.deleteExpiredSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredSessionsStmt: %w", cerr)
		}
	}
	if q.deleteQueryShareStmt != nil {
		if cerr := q.deleteQueryShareStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteQueryShareStmt: %w", cerr)
		}
	}
	if q.deleteSavedQueryStmt != nil {
		if cerr := q.deleteSavedQueryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSavedQueryStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSourceStmt != nil {
		if cerr := q.deleteSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSourceStmt: %w", cerr)
		}
	}
	if q.deleteSystemSettingStmt != nil {
		if cerr := q.deleteSystemSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSystemSettingStmt: %w", cerr)
		}
	}
	if q.deleteTeamStmt != nil {
		if cerr := q.deleteTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTeamStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserSessionsStmt != nil {
		if cerr := q.deleteUserSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserSessionsStmt: %w", cerr)
		}
	}
	if q.failExportJobStmt != nil {
		if cerr := q.failExportJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing failExportJobStmt: %w", cerr)
		}
	}
	if q.getAPITokenStmt != nil {
		if cerr := q.getAPITokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAPITokenStmt: %w", cerr)
		}
	}
	if q.getAPITokenByHashStmt != nil {
		if cerr := q.getAPITokenByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAPITokenByHashStmt: %w", cerr)
		}
	}
	if q.getAlertStmt != nil {
		if cerr := q.getAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAlertStmt: %w", cerr)
		}
	}
	if q.getCollectionStmt != nil {
		if cerr := q.getCollectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCollectionStmt: %w", cerr)
		}
	}
	if q.getCollectionMemberStmt != nil {
		if cerr := q.getCollectionMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCollectionMemberStmt: %w", cerr)
		}
	}
	if q.getDashboardStmt != nil {
		if cerr := q.getDashboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDashboardStmt: %w", cerr)
		}
	}
	if q.getExportJobStmt != nil {
		if cerr := q.getExportJobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExportJobStmt: %w", cerr)
		}
	}
	if q.getLatestUnresolvedAlertHistoryStmt != nil {
		if cerr := q.getLatestUnresolvedAlertHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestUnresolvedAlertHistoryStmt: %w", cerr)
		}
	}
	if q.getPersonalCollectionStmt != nil {
		if cerr := q.getPersonalCollectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPersonalCollectionStmt: %w", cerr)
		}
	}
	if q.getQueryShareStmt != nil {
		if cerr := q.getQueryShareStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getQueryShareStmt: %w", cerr)
		}
	}
	if q.getSavedQueryStmt != nil {
		if cerr := q.getSavedQueryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSavedQueryStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getSourceStmt != nil {
		if cerr := q.getSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSourceStmt: %w", cerr)
		}
	}
	if q.getSourceByIdentityKeyStmt != nil {
		if cerr := q.getSourceByIdentityKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSourceByIdentityKeyStmt: %w", cerr)
		}
	}
	if q.getSourceByNameForProvisioningStmt != nil {
		if cerr := q.getSourceByNameForProvisioningStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSourceByNameForProvisioningStmt: %w", cerr)
		}
	}
	if q.getSystemSettingStmt != nil {
		if cerr := q.getSystemSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSystemSettingStmt: %w", cerr)
		}
	}
	if q.getTeamStmt != nil {
		if cerr := q.getTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamStmt: %w", cerr)
		}
	}
	if q.getTeamByNameStmt != nil {
		if cerr := q.getTeamByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamByNameStmt: %w", cerr)
		}
	}
	if q.getTeamMemberStmt != nil {
		if cerr := q.getTeamMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTeamMemberStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserPreferencesStmt != nil {
		if cerr := q.getUserPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserPreferencesStmt: %w", cerr)
		}
	}
	if q.getUserTeamForSourceStmt != nil {
		if cerr := q.getUserTeamForSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserTeamForSourceStmt: %w", cerr)
		}
	}
	if q.insertAlertHistoryStmt != nil {
		if cerr := q.insertAlertHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAlertHistoryStmt: %w", cerr)
		}
	}
	if q.isSourceManagedStmt != nil {
		if cerr := q.isSourceManagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isSourceManagedStmt: %w", cerr)
		}
	}
	if q.isTeamManagedStmt != nil {
		if cerr := q.isTeamManagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isTeamManagedStmt: %w", cerr)
		}
	}
	if q.isUserManagedStmt != nil {
		if cerr := q.isUserManagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isUserManagedStmt: %w", cerr)
		}
	}
	if q.listAPITokensForUserStmt != nil {
		if cerr := q.listAPITokensForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAPITokensForUserStmt: %w", cerr)
		}
	}
	if q.listAccessibleSourceIDsForUserStmt != nil {
		if cerr := q.listAccessibleSourceIDsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccessibleSourceIDsForUserStmt: %w", cerr)
		}
	}
	if q.listActiveAlertsDueStmt != nil {
		if cerr := q.listActiveAlertsDueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveAlertsDueStmt: %w", cerr)
		}
	}
	if q.listAlertHistoryStmt != nil {
		if cerr := q.listAlertHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAlertHistoryStmt: %w", cerr)
		}
	}
	if q.listAlertsBySourceStmt != nil {
		if cerr := q.listAlertsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAlertsBySourceStmt: %w", cerr)
		}
	}
	if q.listAlertsForUserStmt != nil {
		if cerr := q.listAlertsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAlertsForUserStmt: %w", cerr)
		}
	}
	if q.listAllSavedQueriesStmt != nil {
		if cerr := q.listAllSavedQueriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSavedQueriesStmt: %w", cerr)
		}
	}
	if q.listCollectionItemsStmt != nil {
		if cerr := q.listCollectionItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCollectionItemsStmt: %w", cerr)
		}
	}
	if q.listCollectionMembersStmt != nil {
		if cerr := q.listCollectionMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCollectionMembersStmt: %w", cerr)
		}
	}
	if q.listCollectionsForUserStmt != nil {
		if cerr := q.listCollectionsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCollectionsForUserStmt: %w", cerr)
		}
	}
	if q.listDashboardsStmt != nil {
		if cerr := q.listDashboardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDashboardsStmt: %w", cerr)
		}
	}
	if q.listExpiredExportJobPathsStmt != nil {
		if cerr := q.listExpiredExportJobPathsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExpiredExportJobPathsStmt: %w", cerr)
		}
	}
	if q.listManagedSourcesStmt != nil {
		if cerr := q.listManagedSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listManagedSourcesStmt: %w", cerr)
		}
	}
	if q.listManagedTeamsStmt != nil {
		if cerr := q.listManagedTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listManagedTeamsStmt: %w", cerr)
		}
	}
	if q.listManagedUsersStmt != nil {
		if cerr := q.listManagedUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listManagedUsersStmt: %w", cerr)
		}
	}
	if q.listSavedQueriesForUserStmt != nil {
		if cerr := q.listSavedQueriesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSavedQueriesForUserStmt: %w", cerr)
		}
	}
	if q.listSavedQueriesForUserBySourceStmt != nil {
		if cerr := q.listSavedQueriesForUserBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSavedQueriesForUserBySourceStmt: %w", cerr)
		}
	}
	if q.listServiceAccountsStmt != nil {
		if cerr := q.listServiceAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listServiceAccountsStmt: %w", cerr)
		}
	}
	if q.listSourceTeamsStmt != nil {
		if cerr := q.listSourceTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSourceTeamsStmt: %w", cerr)
		}
	}
	if q.listSourcesStmt != nil {
		if cerr := q.listSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSourcesStmt: %w", cerr)
		}
	}
	if q.listSourcesForUserStmt != nil {
		if cerr := q.listSourcesForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSourcesForUserStmt: %w", cerr)
		}
	}
	if q.listSystemSettingsStmt != nil {
		if cerr := q.listSystemSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSystemSettingsStmt: %w", cerr)
		}
	}
	if q.listSystemSettingsByCategoryStmt != nil {
		if cerr := q.listSystemSettingsByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSystemSettingsByCategoryStmt: %w", cerr)
		}
	}
	if q.listTeamMembersStmt != nil {
		if cerr := q.listTeamMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTeamMembersStmt: %w", cerr)
		}
	}
	if q.listTeamMembersWithDetailsStmt != nil {
		if cerr := q.listTeamMembersWithDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTeamMembersWithDetailsStmt: %w", cerr)
		}
	}
	if q.listTeamSourcesStmt != nil {
		if cerr := q.listTeamSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTeamSourcesStmt: %w", cerr)
		}
	}
	if q.listTeamsStmt != nil {
		if cerr := q.listTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTeamsStmt: %w", cerr)
		}
	}
	if q.listTeamsForUserStmt != nil {
		if cerr := q.listTeamsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTeamsForUserStmt: %w", cerr)
		}
	}
	if q.listUserTeamsStmt != nil {
		if cerr := q.listUserTeamsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserTeamsStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.markAlertEvaluatedStmt != nil {
		if cerr := q.markAlertEvaluatedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAlertEvaluatedStmt: %w", cerr)
		}
	}
	if q.markAlertTriggeredStmt != nil {
		if cerr := q.markAlertTriggeredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markAlertTriggeredStmt: %w", cerr)
		}
	}
	if q.pruneAlertHistoryStmt != nil {
		if cerr := q.pruneAlertHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing pruneAlertHistoryStmt: %w", cerr)
		}
	}
	if q.pruneExpiredQuerySharesStmt != nil {
		if cerr := q.pruneExpiredQuerySharesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing pruneExpiredQuerySharesStmt: %w", cerr)
		}
	}
	if q.removeCollectionItemStmt != nil {
		if cerr := q.removeCollectionItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeCollectionItemStmt: %w", cerr)
		}
	}
	if q.removeCollectionMemberStmt != nil {
		if cerr := q.removeCollectionMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeCollectionMemberStmt: %w", cerr)
		}
	}
	if q.removeTeamMemberStmt != nil {
		if cerr := q.removeTeamMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTeamMemberStmt: %w", cerr)
		}
	}
	if q.removeTeamSourceStmt != nil {
		if cerr := q.removeTeamSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTeamSourceStmt: %w", cerr)
		}
	}
	if q.resolveAlertHistoryStmt != nil {
		if cerr := q.resolveAlertHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveAlertHistoryStmt: %w", cerr)
		}
	}
	if q.setSourceManagedStmt != nil {
		if cerr := q.setSourceManagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setSourceManagedStmt: %w", cerr)
		}
	}
	if q.setTeamManagedStmt != nil {
		if cerr := q.setTeamManagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setTeamManagedStmt: %w", cerr)
		}
	}
	if q.setUserManagedStmt != nil {
		if cerr := q.setUserManagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserManagedStmt: %w", cerr)
		}
	}
	if q.setUserPasswordHashStmt != nil {
		if cerr := q.setUserPasswordHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setUserPasswordHashStmt: %w", cerr)
		}
	}
	if q.teamHasSourceStmt != nil {
		if cerr := q.teamHasSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing teamHasSourceStmt: %w", cerr)
		}
	}
	if q.touchQueryShareStmt != nil {
		if cerr := q.touchQueryShareStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchQueryShareStmt: %w", cerr)
		}
	}
	if q.updateAPITokenLastUsedStmt != nil {
		if cerr := q.updateAPITokenLastUsedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAPITokenLastUsedStmt: %w", cerr)
		}
	}
	if q.updateAlertStmt != nil {
		if cerr := q.updateAlertStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAlertStmt: %w", cerr)
		}
	}
	if q.updateAlertHistoryPayloadStmt != nil {
		if cerr := q.updateAlertHistoryPayloadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAlertHistoryPayloadStmt: %w", cerr)
		}
	}
	if q.updateCollectionStmt != nil {
		if cerr := q.updateCollectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCollectionStmt: %w", cerr)
		}
	}
	if q.updateDashboardStmt != nil {
		if cerr := q.updateDashboardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDashboardStmt: %w", cerr)
		}
	}
	if q.updateExportJobRunningStmt != nil {
		if cerr := q.updateExportJobRunningStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateExportJobRunningStmt: %w", cerr)
		}
	}
	if q.updateSavedQueryStmt != nil {
		if cerr := q.updateSavedQueryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSavedQueryStmt: %w", cerr)
		}
	}
	if q.updateSourceStmt != nil {
		if cerr := q.updateSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSourceStmt: %w", cerr)
		}
	}
	if q.updateTeamStmt != nil {
		if cerr := q.updateTeamStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTeamStmt: %w", cerr)
		}
	}
	if q.updateTeamMemberRoleStmt != nil {
		if cerr := q.updateTeamMemberRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTeamMemberRoleStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.upsertSystemSettingStmt != nil {
		if cerr := q.upsertSystemSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSystemSettingStmt: %w", cerr)
		}
	}
	if q.upsertUserPreferencesStmt != nil {
		if cerr := q.upsertUserPreferencesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertUserPreferencesStmt: %w", cerr)
		}
	}
	if q.userHasSourceAccessStmt != nil {
		if cerr := q.userHasSourceAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userHasSourceAccessStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	addCollectionItemStmt               *sql.Stmt
	addCollectionMemberStmt             *sql.Stmt
	addTeamMemberStmt                   *sql.Stmt
	addTeamSourceStmt                   *sql.Stmt
	completeExportJobStmt               *sql.Stmt
	countAdminUsersStmt                 *sql.Stmt
	countSharedCollectionEditAccessStmt *sql.Stmt
	countUserSessionsStmt               *sql.Stmt
	createAPITokenStmt                  *sql.Stmt
	createAlertStmt                     *sql.Stmt
	createCollectionStmt                *sql.Stmt
	createDashboardStmt                 *sql.Stmt
	createExportJobStmt                 *sql.Stmt
	createQueryShareStmt                *sql.Stmt
	createSavedQueryStmt                *sql.Stmt
	createSessionStmt                   *sql.Stmt
	createSourceStmt                    *sql.Stmt
	createTeamStmt                      *sql.Stmt
	createUserStmt                      *sql.Stmt
	deleteAPITokenStmt                  *sql.Stmt
	deleteAlertStmt                     *sql.Stmt
	deleteCollectionStmt                *sql.Stmt
	deleteDashboardStmt                 *sql.Stmt
	deleteExpiredExportJobsStmt         *sql.Stmt
	deleteExpiredSessionsStmt           *sql.Stmt
	deleteQueryShareStmt                *sql.Stmt
	deleteSavedQueryStmt                *sql.Stmt
	deleteSessionStmt                   *sql.Stmt
	deleteSourceStmt                    *sql.Stmt
	deleteSystemSettingStmt             *sql.Stmt
	deleteTeamStmt                      *sql.Stmt
	deleteUserStmt                      *sql.Stmt
	deleteUserSessionsStmt              *sql.Stmt
	failExportJobStmt                   *sql.Stmt
	getAPITokenStmt                     *sql.Stmt
	getAPITokenByHashStmt               *sql.Stmt
	getAlertStmt                        *sql.Stmt
	getCollectionStmt                   *sql.Stmt
	getCollectionMemberStmt             *sql.Stmt
	getDashboardStmt                    *sql.Stmt
	getExportJobStmt                    *sql.Stmt
	getLatestUnresolvedAlertHistoryStmt *sql.Stmt
	getPersonalCollectionStmt           *sql.Stmt
	getQueryShareStmt                   *sql.Stmt
	getSavedQueryStmt                   *sql.Stmt
	getSessionStmt                      *sql.Stmt
	getSourceStmt                       *sql.Stmt
	getSourceByIdentityKeyStmt          *sql.Stmt
	getSourceByNameForProvisioningStmt  *sql.Stmt
	getSystemSettingStmt                *sql.Stmt
	getTeamStmt                         *sql.Stmt
	getTeamByNameStmt                   *sql.Stmt
	getTeamMemberStmt                   *sql.Stmt
	getUserStmt                         *sql.Stmt
	getUserByEmailStmt                  *sql.Stmt
	getUserPreferencesStmt              *sql.Stmt
	getUserTeamForSourceStmt            *sql.Stmt
	insertAlertHistoryStmt              *sql.Stmt
	isSourceManagedStmt                 *sql.Stmt
	isTeamManagedStmt                   *sql.Stmt
	isUserManagedStmt                   *sql.Stmt
	listAPITokensForUserStmt            *sql.Stmt
	listAccessibleSourceIDsForUserStmt  *sql.Stmt
	listActiveAlertsDueStmt             *sql.Stmt
	listAlertHistoryStmt                *sql.Stmt
	listAlertsBySourceStmt              *sql.Stmt
	listAlertsForUserStmt               *sql.Stmt
	listAllSavedQueriesStmt             *sql.Stmt
	listCollectionItemsStmt             *sql.Stmt
	listCollectionMembersStmt           *sql.Stmt
	listCollectionsForUserStmt          *sql.Stmt
	listDashboardsStmt                  *sql.Stmt
	listExpiredExportJobPathsStmt       *sql.Stmt
	listManagedSourcesStmt              *sql.Stmt
	listManagedTeamsStmt                *sql.Stmt
	listManagedUsersStmt                *sql.Stmt
	listSavedQueriesForUserStmt         *sql.Stmt
	listSavedQueriesForUserBySourceStmt *sql.Stmt
	listServiceAccountsStmt             *sql.Stmt
	listSourceTeamsStmt                 *sql.Stmt
	listSourcesStmt                     *sql.Stmt
	listSourcesForUserStmt              *sql.Stmt
	listSystemSettingsStmt              *sql.Stmt
	listSystemSettingsByCategoryStmt    *sql.Stmt
	listTeamMembersStmt                 *sql.Stmt
	listTeamMembersWithDetailsStmt      *sql.Stmt
	listTeamSourcesStmt                 *sql.Stmt
	listTeamsStmt                       *sql.Stmt
	listTeamsForUserStmt                *sql.Stmt
	listUserTeamsStmt                   *sql.Stmt
	listUsersStmt                       *sql.Stmt
	markAlertEvaluatedStmt              *sql.Stmt
	markAlertTriggeredStmt              *sql.Stmt
	pruneAlertHistoryStmt               *sql.Stmt
	pruneExpiredQuerySharesStmt         *sql.Stmt
	removeCollectionItemStmt            *sql.Stmt
	removeCollectionMemberStmt          *sql.Stmt
	removeTeamMemberStmt                *sql.Stmt
	removeTeamSourceStmt                *sql.Stmt
	resolveAlertHistoryStmt             *sql.Stmt
	setSourceManagedStmt                *sql.Stmt
	setTeamManagedStmt                  *sql.Stmt
	setUserManagedStmt                  *sql.Stmt
	setUserPasswordHashStmt             *sql.Stmt
	teamHasSourceStmt                   *sql.Stmt
	touchQueryShareStmt                 *sql.Stmt
	updateAPITokenLastUsedStmt          *sql.Stmt
	updateAlertStmt                     *sql.Stmt
	updateAlertHistoryPayloadStmt       *sql.Stmt
	updateCollectionStmt                *sql.Stmt
	updateDashboardStmt                 *sql.Stmt
	updateExportJobRunningStmt          *sql.Stmt
	updateSavedQueryStmt                *sql.Stmt
	updateSourceStmt                    *sql.Stmt
	updateTeamStmt                      *sql.Stmt
	updateTeamMemberRoleStmt            *sql.Stmt
	updateUserStmt                      *sql.Stmt
	upsertSystemSettingStmt             *sql.Stmt
	upsertUserPreferencesStmt           *sql.Stmt
	userHasSourceAccessStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		addCollectionItemStmt:               q.addCollectionItemStmt,
		addCollectionMemberStmt:             q.addCollectionMemberStmt,
		addTeamMemberStmt:                   q.addTeamMemberStmt,
		addTeamSourceStmt:                   q.addTeamSourceStmt,
		completeExportJobStmt:               q.completeExportJobStmt,
		countAdminUsersStmt:                 q.countAdminUsersStmt,
		countSharedCollectionEditAccessStmt: q.countSharedCollectionEditAccessStmt,
		countUserSessionsStmt:               q.countUserSessionsStmt,
		createAPITokenStmt:                  q.createAPITokenStmt,
		createAlertStmt:                     q.createAlertStmt,
		createCollectionStmt:                q.createCollectionStmt,
		createDashboardStmt:                 q.createDashboardStmt,
		createExportJobStmt:                 q.createExportJobStmt,
		createQueryShareStmt:                q.createQueryShareStmt,
		createSavedQueryStmt:                q.createSavedQueryStmt,
		createSessionStmt:                   q.createSessionStmt,
		createSourceStmt:                    q.createSourceStmt,
		createTeamStmt:                      q.createTeamStmt,
		createUserStmt:                      q.createUserStmt,
		deleteAPITokenStmt:                  q.deleteAPITokenStmt,
		deleteAlertStmt:                     q.deleteAlertStmt,
		deleteCollectionStmt:                q.deleteCollectionStmt,
		deleteDashboardStmt:                 q.deleteDashboardStmt,
		deleteExpiredExportJobsStmt:         q.deleteExpiredExportJobsStmt,
		deleteExpiredSessionsStmt:           q.deleteExpiredSessionsStmt,
		deleteQueryShareStmt:                q.deleteQueryShareStmt,
		deleteSavedQueryStmt:                q.deleteSavedQueryStmt,
		deleteSessionStmt:                   q.deleteSessionStmt,
		deleteSourceStmt:                    q.deleteSourceStmt,
		deleteSystemSettingStmt:             q.deleteSystemSettingStmt,
		deleteTeamStmt:                      q.deleteTeamStmt,
		deleteUserStmt:                      q.deleteUserStmt,
		deleteUserSessionsStmt:              q.deleteUserSessionsStmt,
		failExportJobStmt:                   q.failExportJobStmt,
		getAPITokenStmt:                     q.getAPITokenStmt,
		getAPITokenByHashStmt:               q.getAPITokenByHashStmt,
		getAlertStmt:                        q.getAlertStmt,
		getCollectionStmt:                   q.getCollectionStmt,
		getCollectionMemberStmt:             q.getCollectionMemberStmt,
		getDashboardStmt:                    q.getDashboardStmt,
		getExportJobStmt:                    q.getExportJobStmt,
		getLatestUnresolvedAlertHistoryStmt: q.getLatestUnresolvedAlertHistoryStmt,
		getPersonalCollectionStmt:           q.getPersonalCollectionStmt,
		getQueryShareStmt:                   q.getQueryShareStmt,
		getSavedQueryStmt:                   q.getSavedQueryStmt,
		getSessionStmt:                      q.getSessionStmt,
		getSourceStmt:                       q.getSourceStmt,
		getSourceByIdentityKeyStmt:          q.getSourceByIdentityKeyStmt,
		getSourceByNameForProvisioningStmt:  q.getSourceByNameForProvisioningStmt,
		getSystemSettingStmt:                q.getSystemSettingStmt,
		getTeamStmt:                         q.getTeamStmt,
		getTeamByNameStmt:                   q.getTeamByNameStmt,
		getTeamMemberStmt:                   q.getTeamMemberStmt,
		getUserStmt:                         q.getUserStmt,
		getUserByEmailStmt:                  q.getUserByEmailStmt,
		getUserPreferencesStmt:              q.getUserPreferencesStmt,
		getUserTeamForSourceStmt:            q.getUserTeamForSourceStmt,
		insertAlertHistoryStmt:              q.insertAlertHistoryStmt,
		isSourceManagedStmt:                 q.isSourceManagedStmt,
		isTeamManagedStmt:                   q.isTeamManagedStmt,
		isUserManagedStmt:                   q.isUserManagedStmt,
		listAPITokensForUserStmt:            q.listAPITokensForUserStmt,
		listAccessibleSourceIDsForUserStmt:  q.listAccessibleSourceIDsForUserStmt,
		listActiveAlertsDueStmt:             q.listActiveAlertsDueStmt,
		listAlertHistoryStmt:                q.listAlertHistoryStmt,
		listAlertsBySourceStmt:              q.listAlertsBySourceStmt,
		listAlertsForUserStmt:               q.listAlertsForUserStmt,
		listAllSavedQueriesStmt:             q.listAllSavedQueriesStmt,
		listCollectionItemsStmt:             q.listCollectionItemsStmt,
		listCollectionMembersStmt:           q.listCollectionMembersStmt,
		listCollectionsForUserStmt:          q.listCollectionsForUserStmt,
		listDashboardsStmt:                  q.listDashboardsStmt,
		listExpiredExportJobPathsStmt:       q.listExpiredExportJobPathsStmt,
		listManagedSourcesStmt:              q.listManagedSourcesStmt,
		listManagedTeamsStmt:                q.listManagedTeamsStmt,
		listManagedUsersStmt:                q.listManagedUsersStmt,
		listSavedQueriesForUserStmt:         q.listSavedQueriesForUserStmt,
		listSavedQueriesForUserBySourceStmt: q.listSavedQueriesForUserBySourceStmt,
		listServiceAccountsStmt:             q.listServiceAccountsStmt,
		listSourceTeamsStmt:                 q.listSourceTeamsStmt,
		listSourcesStmt:                     q.listSourcesStmt,
		listSourcesForUserStmt:              q.listSourcesForUserStmt,
		listSystemSettingsStmt:              q.listSystemSettingsStmt,
		listSystemSettingsByCategoryStmt:    q.listSystemSettingsByCategoryStmt,
		listTeamMembersStmt:                 q.listTeamMembersStmt,
		listTeamMembersWithDetailsStmt:      q.listTeamMembersWithDetailsStmt,
		listTeamSourcesStmt:                 q.listTeamSourcesStmt,
		listTeamsStmt:                       q.listTeamsStmt,
		listTeamsForUserStmt:                q.listTeamsForUserStmt,
		listUserTeamsStmt:                   q.listUserTeamsStmt,
		listUsersStmt:                       q.listUsersStmt,
		markAlertEvaluatedStmt:              q.markAlertEvaluatedStmt,
		markAlertTriggeredStmt:              q.markAlertTriggeredStmt,
		pruneAlertHistoryStmt:               q.pruneAlertHistoryStmt,
		pruneExpiredQuerySharesStmt:         q.pruneExpiredQuerySharesStmt,
		removeCollectionItemStmt:            q.removeCollectionItemStmt,
		removeCollectionMemberStmt:          q.removeCollectionMemberStmt,
		removeTeamMemberStmt:                q.removeTeamMemberStmt,
		removeTeamSourceStmt:                q.removeTeamSourceStmt,
		resolveAlertHistoryStmt:             q.resolveAlertHistoryStmt,
		setSourceManagedStmt:                q.setSourceManagedStmt,
		setTeamManagedStmt:                  q.setTeamManagedStmt,
		setUserManagedStmt:                  q.setUserManagedStmt,
		setUserPasswordHashStmt:             q.setUserPasswordHashStmt,
		teamHasSourceStmt:                   q.teamHasSourceStmt,
		touchQueryShareStmt:                 q.touchQueryShareStmt,
		updateAPITokenLastUsedStmt:          q.updateAPITokenLastUsedStmt,
		updateAlertStmt:                     q.updateAlertStmt,
		updateAlertHistoryPayloadStmt:       q.updateAlertHistoryPayloadStmt,
		updateCollectionStmt:                q.updateCollectionStmt,
		updateDashboardStmt:                 q.updateDashboardStmt,
		updateExportJobRunningStmt:          q.updateExportJobRunningStmt,
		updateSavedQueryStmt:                q.updateSavedQueryStmt,
		updateSourceStmt:                    q.updateSourceStmt,
		updateTeamStmt:                      q.updateTeamStmt,
		updateTeamMemberRoleStmt:            q.updateTeamMemberRoleStmt,
		updateUserStmt:                      q.updateUserStmt,
		upsertSystemSettingStmt:             q.upsertSystemSettingStmt,
		upsertUserPreferencesStmt:           q.upsertUserPreferencesStmt,
		userHasSourceAccessStmt:             q.userHasSourceAccessStmt,
	}
}
