-- Logchef OAuth authorization server storage. Codes and tokens are never
-- stored in plaintext: every *_hash column holds an HMAC-SHA256 hex digest.

-- A grant is one completed consent ("connected app") and one refresh family.
CREATE TABLE oauth_grants (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id      TEXT NOT NULL,
    resource       TEXT NOT NULL,
    scopes         TEXT NOT NULL,
    offline_access BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL,
    last_used_at   TIMESTAMPTZ,
    revoked_at     TIMESTAMPTZ,
    revoke_reason  TEXT
);
CREATE INDEX idx_oauth_grants_user ON oauth_grants(user_id);

CREATE TABLE oauth_auth_requests (
    id               TEXT PRIMARY KEY,
    client_id        TEXT NOT NULL,
    redirect_uri     TEXT NOT NULL,
    resource         TEXT NOT NULL,
    scopes           TEXT NOT NULL,
    offline_access   BOOLEAN NOT NULL DEFAULT FALSE,
    code_challenge   TEXT NOT NULL,
    state            TEXT NOT NULL,
    user_id          BIGINT REFERENCES users(id) ON DELETE CASCADE,
    grant_id         BIGINT REFERENCES oauth_grants(id) ON DELETE CASCADE,
    code_hash        TEXT UNIQUE,
    code_expires_at  TIMESTAMPTZ,
    code_consumed_at TIMESTAMPTZ,
    decided_at       TIMESTAMPTZ,
    denied           BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at       TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_oauth_auth_requests_expires ON oauth_auth_requests(expires_at);

CREATE TABLE oauth_device_authorizations (
    device_code_hash TEXT PRIMARY KEY,
    user_code_hash   TEXT NOT NULL UNIQUE,
    client_id        TEXT NOT NULL,
    resource         TEXT NOT NULL,
    scopes           TEXT NOT NULL,
    offline_access   BOOLEAN NOT NULL DEFAULT FALSE,
    interval_secs    INTEGER NOT NULL,
    last_polled_at   TIMESTAMPTZ,
    user_id          BIGINT REFERENCES users(id) ON DELETE CASCADE,
    grant_id         BIGINT REFERENCES oauth_grants(id) ON DELETE CASCADE,
    approved_at      TIMESTAMPTZ,
    denied_at        TIMESTAMPTZ,
    consumed_at      TIMESTAMPTZ,
    expires_at       TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_oauth_device_authorizations_expires ON oauth_device_authorizations(expires_at);

CREATE TABLE oauth_access_tokens (
    id_hash    TEXT PRIMARY KEY,
    grant_id   BIGINT NOT NULL REFERENCES oauth_grants(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_oauth_access_tokens_grant ON oauth_access_tokens(grant_id);
CREATE INDEX idx_oauth_access_tokens_expires ON oauth_access_tokens(expires_at);

CREATE TABLE oauth_refresh_tokens (
    token_hash       TEXT PRIMARY KEY,
    grant_id         BIGINT NOT NULL REFERENCES oauth_grants(id) ON DELETE CASCADE,
    expires_at       TIMESTAMPTZ NOT NULL,
    consumed_at      TIMESTAMPTZ,
    replaced_by_hash TEXT,
    created_at       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_oauth_refresh_tokens_grant ON oauth_refresh_tokens(grant_id, expires_at);
