-- Consolidated initial schema for the Postgres metadata backend.
-- This is the Postgres translation of the final state produced by the SQLite
-- migration series (internal/sqlite/migrations/000001..000024). Postgres is a
-- new backend with no existing deployments, so it starts from one consolidated
-- schema rather than replaying the SQLite history. Dialect changes vs SQLite:
--   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   0/1 INTEGER CHECK booleans          -> BOOLEAN
--   REAL                                -> DOUBLE PRECISION
--   DATETIME / datetime('now')          -> TIMESTAMPTZ / now()

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT UNIQUE NOT NULL,
    full_name     TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('admin', 'member')),
    status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    last_login_at TIMESTAMPTZ,
    last_active_at TIMESTAMPTZ,
    managed       BOOLEAN NOT NULL DEFAULT FALSE,
    account_type  TEXT NOT NULL DEFAULT 'human' CHECK (account_type IN ('human', 'service')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_created_at ON users(created_at);
CREATE INDEX idx_users_account_type ON users(account_type);

CREATE TABLE sources (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 TEXT NOT NULL,
    _meta_is_auto_created BOOLEAN NOT NULL,
    _meta_ts_field       TEXT NOT NULL DEFAULT '_timestamp',
    _meta_severity_field TEXT DEFAULT 'severity_text',
    host                 TEXT NOT NULL,
    username             TEXT NOT NULL,
    password             TEXT NOT NULL,
    database             TEXT NOT NULL,
    table_name           TEXT NOT NULL,
    description          TEXT,
    ttl_days             BIGINT NOT NULL DEFAULT 0,
    managed              BOOLEAN NOT NULL DEFAULT FALSE,
    secret_ref           TEXT,
    tls_enable           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(database, table_name)
);
CREATE INDEX idx_sources_created_at ON sources(created_at);
CREATE INDEX idx_sources_database_table ON sources(database, table_name);
CREATE INDEX idx_sources_name ON sources(name);

CREATE TABLE teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT UNIQUE NOT NULL,
    description TEXT,
    managed     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_teams_name ON teams(name);
CREATE INDEX idx_teams_created_at ON teams(created_at);

CREATE TABLE sessions (
    id         TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);

CREATE TABLE team_sources (
    team_id    BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    source_id  BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, source_id)
);
CREATE INDEX idx_team_sources_team_id ON team_sources(team_id);
CREATE INDEX idx_team_sources_source_id ON team_sources(source_id);

CREATE TABLE team_members (
    team_id    BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       TEXT NOT NULL CHECK (role IN ('admin', 'member', 'editor')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id)
);
CREATE INDEX idx_team_members_user_id ON team_members(user_id);
CREATE INDEX idx_team_members_team_id ON team_members(team_id);

CREATE TABLE api_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    prefix       TEXT NOT NULL,
    scopes       TEXT NOT NULL DEFAULT '["*"]',
    last_used_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_api_tokens_hash ON api_tokens(token_hash);
CREATE INDEX idx_api_tokens_user_id ON api_tokens(user_id);
CREATE INDEX idx_api_tokens_expires_at ON api_tokens(expires_at);

CREATE TABLE alerts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id               BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    name                    TEXT NOT NULL,
    description             TEXT,
    query_type              TEXT NOT NULL DEFAULT 'sql' CHECK (query_type IN ('sql', 'condition')),
    query                   TEXT,
    condition_json          TEXT,
    lookback_seconds        BIGINT NOT NULL DEFAULT 300,
    threshold_operator      TEXT NOT NULL CHECK (threshold_operator IN ('gt', 'gte', 'lt', 'lte', 'eq', 'neq')),
    threshold_value         DOUBLE PRECISION NOT NULL,
    frequency_seconds       BIGINT NOT NULL DEFAULT 300,
    severity                TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
    labels_json             TEXT,
    annotations_json        TEXT,
    generator_url           TEXT,
    is_active               BOOLEAN NOT NULL DEFAULT TRUE,
    last_state              TEXT NOT NULL DEFAULT 'resolved' CHECK (last_state IN ('firing', 'resolved')),
    last_evaluated_at       TIMESTAMPTZ,
    last_triggered_at       TIMESTAMPTZ,
    recipient_user_ids_json TEXT,
    webhook_urls_json       TEXT,
    created_by              BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_alerts_source ON alerts(source_id);
CREATE INDEX idx_alerts_active ON alerts(is_active);
CREATE INDEX idx_alerts_last_evaluated ON alerts(last_evaluated_at);
CREATE INDEX idx_alerts_last_state ON alerts(last_state);
CREATE INDEX idx_alerts_created_by ON alerts(created_by);

CREATE TABLE alert_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id     BIGINT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
    status       TEXT NOT NULL CHECK (status IN ('triggered', 'resolved', 'error')),
    triggered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at  TIMESTAMPTZ,
    value        DOUBLE PRECISION,
    message      TEXT,
    payload_json TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_alert_history_alert_id ON alert_history(alert_id);
CREATE INDEX idx_alert_history_triggered_at ON alert_history(alert_id, triggered_at DESC);
CREATE INDEX idx_alert_history_alert_status ON alert_history(alert_id, status);

CREATE TABLE system_settings (
    key          TEXT PRIMARY KEY,
    value        TEXT NOT NULL,
    value_type   TEXT NOT NULL CHECK (value_type IN ('string', 'number', 'boolean', 'duration')),
    category     TEXT NOT NULL CHECK (category IN ('alerts', 'ai', 'auth', 'server')),
    description  TEXT,
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_system_settings_category ON system_settings(category);

CREATE TABLE user_preferences (
    user_id          BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    preferences_json TEXT NOT NULL DEFAULT '{}',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE query_shares (
    token            TEXT PRIMARY KEY,
    source_id        BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    created_by       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    team_id          BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    payload_json     TEXT NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    last_accessed_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_query_shares_source ON query_shares(source_id);
CREATE INDEX idx_query_shares_created_by ON query_shares(created_by);
CREATE INDEX idx_query_shares_expires_at ON query_shares(expires_at);

CREATE TABLE export_jobs (
    id            TEXT PRIMARY KEY,
    source_id     BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    created_by    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status        TEXT NOT NULL,
    format        TEXT NOT NULL,
    request_json  TEXT NOT NULL,
    file_name     TEXT,
    file_path     TEXT,
    error_message TEXT,
    rows_exported BIGINT NOT NULL DEFAULT 0,
    bytes_written BIGINT NOT NULL DEFAULT 0,
    expires_at    TIMESTAMPTZ NOT NULL,
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_export_jobs_source ON export_jobs(source_id);
CREATE INDEX idx_export_jobs_created_by ON export_jobs(created_by);
CREATE INDEX idx_export_jobs_expires_at ON export_jobs(expires_at);

CREATE TABLE saved_queries (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id            BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    name                 TEXT NOT NULL,
    description          TEXT,
    query_type           TEXT NOT NULL,
    query_content        TEXT NOT NULL,
    created_by           BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_from_team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_saved_queries_source ON saved_queries(source_id);
CREATE INDEX idx_saved_queries_created_by ON saved_queries(created_by);
CREATE INDEX idx_saved_queries_created_from_team ON saved_queries(created_from_team_id);

CREATE TABLE collections (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    is_personal BOOLEAN NOT NULL DEFAULT FALSE,
    created_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_collections_one_personal_per_user
    ON collections(created_by) WHERE is_personal;
CREATE INDEX idx_collections_created_by ON collections(created_by);

CREATE TABLE collection_items (
    collection_id  BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    saved_query_id BIGINT NOT NULL REFERENCES saved_queries(id) ON DELETE CASCADE,
    sort_order     BIGINT NOT NULL DEFAULT 0,
    added_by       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (collection_id, saved_query_id)
);
CREATE INDEX idx_collection_items_query ON collection_items(saved_query_id);
CREATE INDEX idx_collection_items_collection_order
    ON collection_items(collection_id, sort_order, saved_query_id);

CREATE TABLE collection_members (
    collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role          TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'member')),
    added_by      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (collection_id, user_id)
);
CREATE INDEX idx_collection_members_user ON collection_members(user_id);
