// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID                   int64              `json:"id"`
	SourceID             int64              `json:"source_id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	QueryType            string             `json:"query_type"`
	Query                pgtype.Text        `json:"query"`
	ConditionJson        pgtype.Text        `json:"condition_json"`
	LookbackSeconds      int64              `json:"lookback_seconds"`
	ThresholdOperator    string             `json:"threshold_operator"`
	ThresholdValue       float64            `json:"threshold_value"`
	FrequencySeconds     int64              `json:"frequency_seconds"`
	Severity             string             `json:"severity"`
	LabelsJson           pgtype.Text        `json:"labels_json"`
	AnnotationsJson      pgtype.Text        `json:"annotations_json"`
	GeneratorUrl         pgtype.Text        `json:"generator_url"`
	IsActive             bool               `json:"is_active"`
	LastState            string             `json:"last_state"`
	LastEvaluatedAt      pgtype.Timestamptz `json:"last_evaluated_at"`
	LastTriggeredAt      pgtype.Timestamptz `json:"last_triggered_at"`
	RecipientUserIdsJson pgtype.Text        `json:"recipient_user_ids_json"`
	WebhookUrlsJson      pgtype.Text        `json:"webhook_urls_json"`
	CreatedBy            pgtype.Int8        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AlertHistory struct {
	ID          int64              `json:"id"`
	AlertID     int64              `json:"alert_id"`
	Status      string             `json:"status"`
	TriggeredAt pgtype.Timestamptz `json:"triggered_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	Value       pgtype.Float8      `json:"value"`
	Message     pgtype.Text        `json:"message"`
	PayloadJson pgtype.Text        `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiToken struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Prefix     string             `json:"prefix"`
	Scopes     string             `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Collection struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsPersonal  bool               `json:"is_personal"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CollectionItem struct {
	CollectionID int64              `json:"collection_id"`
	SavedQueryID int64              `json:"saved_query_id"`
	SortOrder    int64              `json:"sort_order"`
	AddedBy      pgtype.Int8        `json:"added_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CollectionMember struct {
	CollectionID int64              `json:"collection_id"`
	UserID       int64              `json:"user_id"`
	Role         string             `json:"role"`
	AddedBy      pgtype.Int8        `json:"added_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ExportJob struct {
	ID           string             `json:"id"`
	SourceID     int64              `json:"source_id"`
	CreatedBy    int64              `json:"created_by"`
	Status       string             `json:"status"`
	Format       string             `json:"format"`
	RequestJson  string             `json:"request_json"`
	FileName     pgtype.Text        `json:"file_name"`
	FilePath     pgtype.Text        `json:"file_path"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RowsExported int64              `json:"rows_exported"`
	BytesWritten int64              `json:"bytes_written"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type QueryShare struct {
	Token          string             `json:"token"`
	SourceID       int64              `json:"source_id"`
	CreatedBy      int64              `json:"created_by"`
	TeamID         pgtype.Int8        `json:"team_id"`
	PayloadJson    string             `json:"payload_json"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SavedQuery struct {
	ID                int64              `json:"id"`
	SourceID          int64              `json:"source_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	QueryType         string             `json:"query_type"`
	QueryContent      string             `json:"query_content"`
	CreatedBy         pgtype.Int8        `json:"created_by"`
	CreatedFromTeamID pgtype.Int8        `json:"created_from_team_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Source struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	MetaIsAutoCreated bool               `json:"_meta_is_auto_created"`
	MetaTsField       string             `json:"_meta_ts_field"`
	MetaSeverityField pgtype.Text        `json:"_meta_severity_field"`
	Host              string             `json:"host"`
	Username          string             `json:"username"`
	Password          string             `json:"password"`
	Database          string             `json:"database"`
	TableName         string             `json:"table_name"`
	Description       pgtype.Text        `json:"description"`
	TtlDays           int64              `json:"ttl_days"`
	Managed           bool               `json:"managed"`
	SecretRef         pgtype.Text        `json:"secret_ref"`
	TlsEnable         bool               `json:"tls_enable"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SystemSetting struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	ValueType   string             `json:"value_type"`
	Category    string             `json:"category"`
	Description pgtype.Text        `json:"description"`
	IsSensitive bool               `json:"is_sensitive"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Managed     bool               `json:"managed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TeamMember struct {
	TeamID    int64              `json:"team_id"`
	UserID    int64              `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamSource struct {
	TeamID    int64              `json:"team_id"`
	SourceID  int64              `json:"source_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	Managed      bool               `json:"managed"`
	AccountType  string             `json:"account_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserPreference struct {
	UserID          int64              `json:"user_id"`
	PreferencesJson string             `json:"preferences_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
