// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Add a saved query to a collection; idempotent on (collection_id, saved_query_id).
	AddCollectionItem(ctx context.Context, arg AddCollectionItemParams) error
	// Add a member; idempotent on (collection_id, user_id).
	AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error
	// Team Members
	// Add a member to a team
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	// Team Sources
	// Add a data source to a team
	AddTeamSource(ctx context.Context, arg AddTeamSourceParams) error
	// Mark an export job as complete and return its ID
	CompleteExportJob(ctx context.Context, arg CompleteExportJobParams) (string, error)
	// Count active admin users
	CountAdminUsers(ctx context.Context, arg CountAdminUsersParams) (int64, error)
	// Count shared (non-personal) collections that contain the given saved query and
	// in which the user is an owner or editor. A non-zero count means the user has
	// delegated edit rights on that query via collection membership.
	CountSharedCollectionEditAccess(ctx context.Context, arg CountSharedCollectionEditAccessParams) (int64, error)
	// Count active sessions for a user
	CountUserSessions(ctx context.Context, arg CountUserSessionsParams) (int64, error)
	// API Tokens
	// Create a new API token
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (int64, error)
	// Alerts
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	// Collections (cross-team curation lists for saved queries)
	// Insert a new collection (personal or shared)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (CreateCollectionRow, error)
	// Dashboards -----------------------------------------------------------------
	// Insert a new dashboard and return its id.
	CreateDashboard(ctx context.Context, arg CreateDashboardParams) (int64, error)
	// Export Jobs
	// Persist an async export job
	CreateExportJob(ctx context.Context, arg CreateExportJobParams) error
	// Query Shares
	// Persist an ad hoc query share token
	CreateQueryShare(ctx context.Context, arg CreateQueryShareParams) error
	// Saved Queries (cross-team, source-scoped)
	// Insert a new saved query and return its id
	CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (int64, error)
	// Sessions
	// Create a new session
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// Sources
	// Create a new source entry
	CreateSource(ctx context.Context, arg CreateSourceParams) (int64, error)
	// Teams
	// Create a new team
	CreateTeam(ctx context.Context, arg CreateTeamParams) (int64, error)
	// Users
	// Create a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	// Delete an API token by ID and user ID (ensure user owns the token)
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error
	DeleteAlert(ctx context.Context, id int64) (int64, error)
	// Delete a collection. Personal collections cannot be deleted (enforced in app code).
	DeleteCollection(ctx context.Context, id int64) error
	// Delete a dashboard; RETURNING lets callers detect not-found.
	DeleteDashboard(ctx context.Context, id int64) (int64, error)
	// Delete expired export jobs
	DeleteExpiredExportJobs(ctx context.Context, expiresAt pgtype.Timestamptz) error
	// Delete all sessions whose expiry is at or before the given time
	DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) error
	// Delete a query share and return its token
	DeleteQueryShare(ctx context.Context, token string) (string, error)
	// Delete a saved query
	DeleteSavedQuery(ctx context.Context, id int64) error
	// Delete a session by ID
	DeleteSession(ctx context.Context, id string) error
	// Delete a source by ID
	DeleteSource(ctx context.Context, id int64) error
	DeleteSystemSetting(ctx context.Context, key string) error
	// Delete a team by ID
	DeleteTeam(ctx context.Context, id int64) error
	// Delete a user by ID
	DeleteUser(ctx context.Context, id int64) error
	// Delete all sessions for a user
	DeleteUserSessions(ctx context.Context, userID int64) error
	// Mark an export job as failed and return its ID
	FailExportJob(ctx context.Context, arg FailExportJobParams) (string, error)
	// Get an API token by ID
	GetAPIToken(ctx context.Context, id int64) (ApiToken, error)
	// Get an API token by its hash (for authentication)
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAlert(ctx context.Context, id int64) (Alert, error)
	// Look up a collection by id
	GetCollection(ctx context.Context, id int64) (Collection, error)
	// Look up a single membership row
	GetCollectionMember(ctx context.Context, arg GetCollectionMemberParams) (CollectionMember, error)
	// Look up one dashboard by id, with creator identity like ListDashboards.
	GetDashboard(ctx context.Context, id int64) (GetDashboardRow, error)
	// Retrieve an export job by ID
	GetExportJob(ctx context.Context, id string) (ExportJob, error)
	GetLatestUnresolvedAlertHistory(ctx context.Context, alertID int64) (AlertHistory, error)
	// Find the caller's personal collection if it exists
	GetPersonalCollection(ctx context.Context, createdBy pgtype.Int8) (Collection, error)
	// Retrieve an ad hoc query share by token with creator details
	GetQueryShare(ctx context.Context, token string) (GetQueryShareRow, error)
	// Look up one saved query by id
	GetSavedQuery(ctx context.Context, id int64) (SavedQuery, error)
	// Get a session by ID
	GetSession(ctx context.Context, id string) (Session, error)
	// Get a single source by ID
	GetSource(ctx context.Context, id int64) (Source, error)
	// Get a single source by provider-computed identity key
	GetSourceByIdentityKey(ctx context.Context, identityKey string) (Source, error)
	// Get source by name for provisioning lookup
	GetSourceByNameForProvisioning(ctx context.Context, name string) (Source, error)
	// System Settings Queries
	GetSystemSetting(ctx context.Context, key string) (SystemSetting, error)
	// Get a team by ID
	GetTeam(ctx context.Context, id int64) (Team, error)
	// Get a team by its name
	GetTeamByName(ctx context.Context, name string) (Team, error)
	// Get a team member
	GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error)
	// Get a user by ID
	GetUser(ctx context.Context, id int64) (User, error)
	// Get a user by email
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// User Preferences
	// Get user preferences by user ID
	GetUserPreferences(ctx context.Context, userID int64) (UserPreference, error)
	// Get a team ID that the user belongs to and that has access to the source
	GetUserTeamForSource(ctx context.Context, arg GetUserTeamForSourceParams) (int64, error)
	// Alert history queries
	InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error)
	// Check if a source is managed
	IsSourceManaged(ctx context.Context, id int64) (bool, error)
	// Check if a team is managed
	IsTeamManaged(ctx context.Context, id int64) (bool, error)
	// Check if a user is managed
	IsUserManaged(ctx context.Context, id int64) (bool, error)
	// List all API tokens for a user
	ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error)
	ListActiveAlertsDue(ctx context.Context) ([]Alert, error)
	ListAlertHistory(ctx context.Context, arg ListAlertHistoryParams) ([]AlertHistory, error)
	// List alerts for one source
	ListAlertsBySource(ctx context.Context, sourceID int64) ([]Alert, error)
	// List every alert the user can see (any source attached to any of their teams)
	ListAlertsForUser(ctx context.Context, userID int64) ([]Alert, error)
	// List every saved query without a source-access gate. This is only for the
	// global-admin browse surface; callers must authorize before invoking it.
	ListAllSavedQueries(ctx context.Context) ([]ListAllSavedQueriesRow, error)
	// List items in a collection with saved-query details
	ListCollectionItems(ctx context.Context, collectionID int64) ([]ListCollectionItemsRow, error)
	// List members of a collection with user details
	ListCollectionMembers(ctx context.Context, collectionID int64) ([]ListCollectionMembersRow, error)
	// List collections the user owns or is a member of, with member count and item count
	ListCollectionsForUser(ctx context.Context, userID int64) ([]ListCollectionsForUserRow, error)
	// List every dashboard, newest-updated first, with the creator's email/name via
	// a LEFT JOIN (NULL for dashboards whose author was deleted).
	ListDashboards(ctx context.Context) ([]ListDashboardsRow, error)
	// List artifact paths for expired export jobs
	ListExpiredExportJobPaths(ctx context.Context, expiresAt pgtype.Timestamptz) ([]pgtype.Text, error)
	// Provisioning Queries
	// Get all sources managed by provisioning config
	ListManagedSources(ctx context.Context) ([]Source, error)
	// Get all teams managed by provisioning config
	ListManagedTeams(ctx context.Context) ([]Team, error)
	// Get all users managed by provisioning config
	ListManagedUsers(ctx context.Context) ([]User, error)
	// List every saved query the user can see (any source attached to any of their teams)
	ListSavedQueriesForUser(ctx context.Context, userID int64) ([]ListSavedQueriesForUserRow, error)
	// List saved queries for a specific source, scoped to a user that has access to it
	ListSavedQueriesForUserBySource(ctx context.Context, arg ListSavedQueriesForUserBySourceParams) ([]ListSavedQueriesForUserBySourceRow, error)
	// List service principals
	ListServiceAccounts(ctx context.Context) ([]User, error)
	// List all teams a data source is a member of
	ListSourceTeams(ctx context.Context, sourceID int64) ([]Team, error)
	// Get all sources ordered by creation date
	ListSources(ctx context.Context) ([]Source, error)
	// List all sources a user has access to
	ListSourcesForUser(ctx context.Context, userID int64) ([]Source, error)
	ListSystemSettings(ctx context.Context) ([]SystemSetting, error)
	ListSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error)
	// List all members of a team
	ListTeamMembers(ctx context.Context, teamID int64) ([]TeamMember, error)
	// List all members of a team with user details
	ListTeamMembersWithDetails(ctx context.Context, teamID int64) ([]ListTeamMembersWithDetailsRow, error)
	// List all data sources in a team
	ListTeamSources(ctx context.Context, teamID int64) ([]Source, error)
	// List all teams
	ListTeams(ctx context.Context) ([]ListTeamsRow, error)
	// List all teams a user is a member of
	ListTeamsForUser(ctx context.Context, userID int64) ([]ListTeamsForUserRow, error)
	// List all teams a user is a member of
	ListUserTeams(ctx context.Context, userID int64) ([]Team, error)
	// List all users
	ListUsers(ctx context.Context) ([]User, error)
	MarkAlertEvaluated(ctx context.Context, id int64) error
	MarkAlertTriggered(ctx context.Context, id int64) error
	PruneAlertHistory(ctx context.Context, arg PruneAlertHistoryParams) error
	// Delete expired query shares
	PruneExpiredQueryShares(ctx context.Context, expiresAt pgtype.Timestamptz) error
	// Remove an item from a collection
	RemoveCollectionItem(ctx context.Context, arg RemoveCollectionItemParams) error
	// Remove a member from a collection
	RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) error
	// Remove a member from a team
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	// Remove a data source from a team
	RemoveTeamSource(ctx context.Context, arg RemoveTeamSourceParams) error
	ResolveAlertHistory(ctx context.Context, arg ResolveAlertHistoryParams) (int64, error)
	// Mark a source as managed/unmanaged and set secret_ref
	SetSourceManaged(ctx context.Context, arg SetSourceManagedParams) error
	// Mark a team as managed/unmanaged
	SetTeamManaged(ctx context.Context, arg SetTeamManagedParams) error
	// Mark a user as managed/unmanaged
	SetUserManaged(ctx context.Context, arg SetUserManagedParams) error
	// Set (or clear) a user's local-auth bcrypt hash
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	// Additional queries for user-source and team-source access
	// Check if a team has access to a source
	TeamHasSource(ctx context.Context, arg TeamHasSourceParams) (bool, error)
	// Update a query share's last access time
	TouchQueryShare(ctx context.Context, arg TouchQueryShareParams) error
	// Update the last used timestamp for an API token
	UpdateAPITokenLastUsed(ctx context.Context, id int64) error
	UpdateAlert(ctx context.Context, arg UpdateAlertParams) (int64, error)
	UpdateAlertHistoryPayload(ctx context.Context, arg UpdateAlertHistoryPayloadParams) (int64, error)
	// Update name/description (owner only - enforced in app code)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error
	// Update a dashboard's mutable fields; RETURNING lets callers detect not-found.
	UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (int64, error)
	// Mark an export job as running and return its ID
	UpdateExportJobRunning(ctx context.Context, arg UpdateExportJobRunningParams) (string, error)
	// Update a saved query's mutable fields
	UpdateSavedQuery(ctx context.Context, arg UpdateSavedQueryParams) error
	// Update an existing source
	UpdateSource(ctx context.Context, arg UpdateSourceParams) error
	// Update a team
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) error
	// Update a team member's role
	UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error
	// Update a user
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error
	// Insert or update user preferences
	UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error
	// Check if a user has access to a source through any team
	UserHasSourceAccess(ctx context.Context, arg UserHasSourceAccessParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
