// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCollectionItem = `-- name: AddCollectionItem :exec
INSERT INTO collection_items (collection_id, saved_query_id, sort_order, added_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT(collection_id, saved_query_id) DO NOTHING
`

type AddCollectionItemParams struct {
	CollectionID int64       `json:"collection_id"`
	SavedQueryID int64       `json:"saved_query_id"`
	SortOrder    int64       `json:"sort_order"`
	AddedBy      pgtype.Int8 `json:"added_by"`
}

// Add a saved query to a collection; idempotent on (collection_id, saved_query_id).
func (q *Queries) AddCollectionItem(ctx context.Context, arg AddCollectionItemParams) error {
	_, err := q.db.Exec(ctx, addCollectionItem,
		arg.CollectionID,
		arg.SavedQueryID,
		arg.SortOrder,
		arg.AddedBy,
	)
	return err
}

const addCollectionMember = `-- name: AddCollectionMember :exec
INSERT INTO collection_members (collection_id, user_id, role, added_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT(collection_id, user_id) DO NOTHING
`

type AddCollectionMemberParams struct {
	CollectionID int64       `json:"collection_id"`
	UserID       int64       `json:"user_id"`
	Role         string      `json:"role"`
	AddedBy      pgtype.Int8 `json:"added_by"`
}

// Add a member; idempotent on (collection_id, user_id).
func (q *Queries) AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error {
	_, err := q.db.Exec(ctx, addCollectionMember,
		arg.CollectionID,
		arg.UserID,
		arg.Role,
		arg.AddedBy,
	)
	return err
}

const addTeamMember = `-- name: AddTeamMember :exec

INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddTeamMemberParams struct {
	TeamID int64  `json:"team_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

// Team Members
// Add a member to a team
func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const addTeamSource = `-- name: AddTeamSource :exec

INSERT INTO team_sources (team_id, source_id)
VALUES ($1, $2)
`

type AddTeamSourceParams struct {
	TeamID   int64 `json:"team_id"`
	SourceID int64 `json:"source_id"`
}

// Team Sources
// Add a data source to a team
func (q *Queries) AddTeamSource(ctx context.Context, arg AddTeamSourceParams) error {
	_, err := q.db.Exec(ctx, addTeamSource, arg.TeamID, arg.SourceID)
	return err
}

const completeExportJob = `-- name: CompleteExportJob :one
UPDATE export_jobs
SET
    status = $1,
    file_name = $2,
    file_path = $3,
    error_message = NULL,
    rows_exported = $4,
    bytes_written = $5,
    completed_at = $6,
    updated_at = $7
WHERE id = $8
RETURNING id
`

type CompleteExportJobParams struct {
	Status       string             `json:"status"`
	FileName     pgtype.Text        `json:"file_name"`
	FilePath     pgtype.Text        `json:"file_path"`
	RowsExported int64              `json:"rows_exported"`
	BytesWritten int64              `json:"bytes_written"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           string             `json:"id"`
}

// Mark an export job as complete and return its ID
func (q *Queries) CompleteExportJob(ctx context.Context, arg CompleteExportJobParams) (string, error) {
	row := q.db.QueryRow(ctx, completeExportJob,
		arg.Status,
		arg.FileName,
		arg.FilePath,
		arg.RowsExported,
		arg.BytesWritten,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM users WHERE role = $1 AND status = $2
`

type CountAdminUsersParams struct {
	Role   string `json:"role"`
	Status string `json:"status"`
}

// Count active admin users
func (q *Queries) CountAdminUsers(ctx context.Context, arg CountAdminUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers, arg.Role, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSharedCollectionEditAccess = `-- name: CountSharedCollectionEditAccess :one
SELECT COUNT(*)
FROM collection_items ci
JOIN collections c ON c.id = ci.collection_id
JOIN collection_members cm ON cm.collection_id = ci.collection_id
WHERE ci.saved_query_id = $1
  AND cm.user_id = $2
  AND c.is_personal = false
  AND cm.role IN ('owner', 'editor')
`

type CountSharedCollectionEditAccessParams struct {
	SavedQueryID int64 `json:"saved_query_id"`
	UserID       int64 `json:"user_id"`
}

// Count shared (non-personal) collections that contain the given saved query and
// in which the user is an owner or editor. A non-zero count means the user has
// delegated edit rights on that query via collection membership.
func (q *Queries) CountSharedCollectionEditAccess(ctx context.Context, arg CountSharedCollectionEditAccessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSharedCollectionEditAccess, arg.SavedQueryID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSessions = `-- name: CountUserSessions :one
SELECT COUNT(*) FROM sessions WHERE user_id = $1 AND expires_at > $2
`

type CountUserSessionsParams struct {
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Count active sessions for a user
func (q *Queries) CountUserSessions(ctx context.Context, arg CountUserSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserSessions, arg.UserID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, name, token_hash, prefix, expires_at, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateAPITokenParams struct {
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	Prefix    string             `json:"prefix"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Scopes    string             `json:"scopes"`
}

// API Tokens
// Create a new API token
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAlert = `-- name: CreateAlert :one

INSERT INTO alerts (
    source_id,
    name,
    description,
    query_language,
    editor_mode,
    query,
    condition_json,
    lookback_seconds,
    threshold_operator,
    threshold_value,
    frequency_seconds,
    severity,
    labels_json,
    annotations_json,
    recipient_user_ids_json,
    webhook_urls_json,
    generator_url,
    is_active,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, source_id, name, description, query, condition_json, lookback_seconds, threshold_operator, threshold_value, frequency_seconds, severity, labels_json, annotations_json, generator_url, is_active, last_state, last_evaluated_at, last_triggered_at, recipient_user_ids_json, webhook_urls_json, created_by, created_at, updated_at, query_language, editor_mode
`

type CreateAlertParams struct {
	SourceID             int64       `json:"source_id"`
	Name                 string      `json:"name"`
	Description          pgtype.Text `json:"description"`
	QueryLanguage        string      `json:"query_language"`
	EditorMode           string      `json:"editor_mode"`
	Query                pgtype.Text `json:"query"`
	ConditionJson        pgtype.Text `json:"condition_json"`
	LookbackSeconds      int64       `json:"lookback_seconds"`
	ThresholdOperator    string      `json:"threshold_operator"`
	ThresholdValue       float64     `json:"threshold_value"`
	FrequencySeconds     int64       `json:"frequency_seconds"`
	Severity             string      `json:"severity"`
	LabelsJson           pgtype.Text `json:"labels_json"`
	AnnotationsJson      pgtype.Text `json:"annotations_json"`
	RecipientUserIdsJson pgtype.Text `json:"recipient_user_ids_json"`
	WebhookUrlsJson      pgtype.Text `json:"webhook_urls_json"`
	GeneratorUrl         pgtype.Text `json:"generator_url"`
	IsActive             bool        `json:"is_active"`
	CreatedBy            pgtype.Int8 `json:"created_by"`
}

// Alerts
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.SourceID,
		arg.Name,
		arg.Description,
		arg.QueryLanguage,
		arg.EditorMode,
		arg.Query,
		arg.ConditionJson,
		arg.LookbackSeconds,
		arg.ThresholdOperator,
		arg.ThresholdValue,
		arg.FrequencySeconds,
		arg.Severity,
		arg.LabelsJson,
		arg.AnnotationsJson,
		arg.RecipientUserIdsJson,
		arg.WebhookUrlsJson,
		arg.GeneratorUrl,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.ConditionJson,
		&i.LookbackSeconds,
		&i.ThresholdOperator,
		&i.ThresholdValue,
		&i.FrequencySeconds,
		&i.Severity,
		&i.LabelsJson,
		&i.AnnotationsJson,
		&i.GeneratorUrl,
		&i.IsActive,
		&i.LastState,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.RecipientUserIdsJson,
		&i.WebhookUrlsJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueryLanguage,
		&i.EditorMode,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one

INSERT INTO collections (name, description, is_personal, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at
`

type CreateCollectionParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsPersonal  bool        `json:"is_personal"`
	CreatedBy   pgtype.Int8 `json:"created_by"`
}

type CreateCollectionRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Collections (cross-team curation lists for saved queries)
// Insert a new collection (personal or shared)
func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (CreateCollectionRow, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.Name,
		arg.Description,
		arg.IsPersonal,
		arg.CreatedBy,
	)
	var i CreateCollectionRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createExportJob = `-- name: CreateExportJob :exec

INSERT INTO export_jobs (
    id,
    source_id,
    created_by,
    status,
    format,
    request_json,
    expires_at,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateExportJobParams struct {
	ID          string             `json:"id"`
	SourceID    int64              `json:"source_id"`
	CreatedBy   int64              `json:"created_by"`
	Status      string             `json:"status"`
	Format      string             `json:"format"`
	RequestJson string             `json:"request_json"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Export Jobs
// Persist an async export job
func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) error {
	_, err := q.db.Exec(ctx, createExportJob,
		arg.ID,
		arg.SourceID,
		arg.CreatedBy,
		arg.Status,
		arg.Format,
		arg.RequestJson,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createQueryShare = `-- name: CreateQueryShare :exec

INSERT INTO query_shares (
    token,
    source_id,
    team_id,
    created_by,
    payload_json,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateQueryShareParams struct {
	Token       string             `json:"token"`
	SourceID    int64              `json:"source_id"`
	TeamID      pgtype.Int8        `json:"team_id"`
	CreatedBy   int64              `json:"created_by"`
	PayloadJson string             `json:"payload_json"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Query Shares
// Persist an ad hoc query share token
func (q *Queries) CreateQueryShare(ctx context.Context, arg CreateQueryShareParams) error {
	_, err := q.db.Exec(ctx, createQueryShare,
		arg.Token,
		arg.SourceID,
		arg.TeamID,
		arg.CreatedBy,
		arg.PayloadJson,
		arg.ExpiresAt,
	)
	return err
}

const createSavedQuery = `-- name: CreateSavedQuery :one

INSERT INTO saved_queries (source_id, created_from_team_id, name, description, query_language, editor_mode, query_content, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateSavedQueryParams struct {
	SourceID          int64       `json:"source_id"`
	CreatedFromTeamID pgtype.Int8 `json:"created_from_team_id"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	QueryLanguage     string      `json:"query_language"`
	EditorMode        string      `json:"editor_mode"`
	QueryContent      string      `json:"query_content"`
	CreatedBy         pgtype.Int8 `json:"created_by"`
}

// Saved Queries (cross-team, source-scoped)
// Insert a new saved query and return its id
func (q *Queries) CreateSavedQuery(ctx context.Context, arg CreateSavedQueryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSavedQuery,
		arg.SourceID,
		arg.CreatedFromTeamID,
		arg.Name,
		arg.Description,
		arg.QueryLanguage,
		arg.EditorMode,
		arg.QueryContent,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (id, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Sessions
// Create a new session
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createSource = `-- name: CreateSource :one

INSERT INTO sources (
    name, _meta_is_auto_created, source_type, _meta_ts_field, _meta_severity_field, connection_config, identity_key, description, ttl_days, managed, secret_ref, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now())
RETURNING id
`

type CreateSourceParams struct {
	Name              string      `json:"name"`
	MetaIsAutoCreated bool        `json:"_meta_is_auto_created"`
	SourceType        string      `json:"source_type"`
	MetaTsField       string      `json:"_meta_ts_field"`
	MetaSeverityField pgtype.Text `json:"_meta_severity_field"`
	ConnectionConfig  []byte      `json:"connection_config"`
	IdentityKey       string      `json:"identity_key"`
	Description       pgtype.Text `json:"description"`
	TtlDays           int64       `json:"ttl_days"`
	Managed           bool        `json:"managed"`
	SecretRef         pgtype.Text `json:"secret_ref"`
}

// Sources
// Create a new source entry
func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.Name,
		arg.MetaIsAutoCreated,
		arg.SourceType,
		arg.MetaTsField,
		arg.MetaSeverityField,
		arg.ConnectionConfig,
		arg.IdentityKey,
		arg.Description,
		arg.TtlDays,
		arg.Managed,
		arg.SecretRef,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (name, description)
VALUES ($1, $2)
RETURNING id
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

// Teams
// Create a new team
func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, full_name, role, status, last_login_at, account_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateUserParams struct {
	Email       string             `json:"email"`
	FullName    string             `json:"full_name"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	AccountType string             `json:"account_type"`
}

// Users
// Create a new user
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.Status,
		arg.LastLoginAt,
		arg.AccountType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteAPITokenParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Delete an API token by ID and user ID (ensure user owns the token)
func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	return err
}

const deleteAlert = `-- name: DeleteAlert :one
DELETE FROM alerts WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteAlert(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteAlert, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

// Delete a collection. Personal collections cannot be deleted (enforced in app code).
func (q *Queries) DeleteCollection(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const deleteExpiredExportJobs = `-- name: DeleteExpiredExportJobs :exec
DELETE FROM export_jobs
WHERE expires_at < $1
`

// Delete expired export jobs
func (q *Queries) DeleteExpiredExportJobs(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredExportJobs, expiresAt)
	return err
}

const deleteQueryShare = `-- name: DeleteQueryShare :one
DELETE FROM query_shares
WHERE token = $1
RETURNING token
`

// Delete a query share and return its token
func (q *Queries) DeleteQueryShare(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, deleteQueryShare, token)
	var token_2 string
	err := row.Scan(&token_2)
	return token_2, err
}

const deleteSavedQuery = `-- name: DeleteSavedQuery :exec
DELETE FROM saved_queries WHERE id = $1
`

// Delete a saved query
func (q *Queries) DeleteSavedQuery(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSavedQuery, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

// Delete a session by ID
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = $1
`

// Delete a source by ID
func (q *Queries) DeleteSource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSource, id)
	return err
}

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings
WHERE key = $1
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSystemSetting, key)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

// Delete a team by ID
func (q *Queries) DeleteTeam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// Delete a user by ID
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

// Delete all sessions for a user
func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const failExportJob = `-- name: FailExportJob :one
UPDATE export_jobs
SET
    status = $1,
    file_name = NULL,
    file_path = NULL,
    error_message = $2,
    completed_at = NULL,
    updated_at = $3
WHERE id = $4
RETURNING id
`

type FailExportJobParams struct {
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           string             `json:"id"`
}

// Mark an export job as failed and return its ID
func (q *Queries) FailExportJob(ctx context.Context, arg FailExportJobParams) (string, error) {
	row := q.db.QueryRow(ctx, failExportJob,
		arg.Status,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, created_at, updated_at FROM api_tokens WHERE id = $1
`

// Get an API token by ID
func (q *Queries) GetAPIToken(ctx context.Context, id int64) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPIToken, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, created_at, updated_at FROM api_tokens WHERE token_hash = $1
`

// Get an API token by its hash (for authentication)
func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlert = `-- name: GetAlert :one
SELECT id, source_id, name, description, query, condition_json, lookback_seconds, threshold_operator, threshold_value, frequency_seconds, severity, labels_json, annotations_json, generator_url, is_active, last_state, last_evaluated_at, last_triggered_at, recipient_user_ids_json, webhook_urls_json, created_by, created_at, updated_at, query_language, editor_mode FROM alerts WHERE id = $1
`

func (q *Queries) GetAlert(ctx context.Context, id int64) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.ConditionJson,
		&i.LookbackSeconds,
		&i.ThresholdOperator,
		&i.ThresholdValue,
		&i.FrequencySeconds,
		&i.Severity,
		&i.LabelsJson,
		&i.AnnotationsJson,
		&i.GeneratorUrl,
		&i.IsActive,
		&i.LastState,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.RecipientUserIdsJson,
		&i.WebhookUrlsJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueryLanguage,
		&i.EditorMode,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, description, is_personal, created_by, created_at, updated_at FROM collections WHERE id = $1
`

// Look up a collection by id
func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionMember = `-- name: GetCollectionMember :one
SELECT collection_id, user_id, role, added_by, created_at
FROM collection_members
WHERE collection_id = $1 AND user_id = $2
`

type GetCollectionMemberParams struct {
	CollectionID int64 `json:"collection_id"`
	UserID       int64 `json:"user_id"`
}

// Look up a single membership row
func (q *Queries) GetCollectionMember(ctx context.Context, arg GetCollectionMemberParams) (CollectionMember, error) {
	row := q.db.QueryRow(ctx, getCollectionMember, arg.CollectionID, arg.UserID)
	var i CollectionMember
	err := row.Scan(
		&i.CollectionID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getExportJob = `-- name: GetExportJob :one
SELECT
    id,
    source_id,
    created_by,
    status,
    format,
    request_json,
    file_name,
    file_path,
    error_message,
    rows_exported,
    bytes_written,
    expires_at,
    completed_at,
    created_at,
    updated_at
FROM export_jobs
WHERE id = $1
`

// Retrieve an export job by ID
func (q *Queries) GetExportJob(ctx context.Context, id string) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJob, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.CreatedBy,
		&i.Status,
		&i.Format,
		&i.RequestJson,
		&i.FileName,
		&i.FilePath,
		&i.ErrorMessage,
		&i.RowsExported,
		&i.BytesWritten,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestUnresolvedAlertHistory = `-- name: GetLatestUnresolvedAlertHistory :one
SELECT id, alert_id, status, triggered_at, resolved_at, value, message, payload_json, created_at FROM alert_history
WHERE alert_id = $1 AND status = 'triggered'
ORDER BY triggered_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestUnresolvedAlertHistory(ctx context.Context, alertID int64) (AlertHistory, error) {
	row := q.db.QueryRow(ctx, getLatestUnresolvedAlertHistory, alertID)
	var i AlertHistory
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Status,
		&i.TriggeredAt,
		&i.ResolvedAt,
		&i.Value,
		&i.Message,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalCollection = `-- name: GetPersonalCollection :one
SELECT id, name, description, is_personal, created_by, created_at, updated_at FROM collections WHERE created_by = $1 AND is_personal = true
`

// Find the caller's personal collection if it exists
func (q *Queries) GetPersonalCollection(ctx context.Context, createdBy pgtype.Int8) (Collection, error) {
	row := q.db.QueryRow(ctx, getPersonalCollection, createdBy)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueryShare = `-- name: GetQueryShare :one
SELECT
    qs.token,
    qs.source_id,
    qs.team_id,
    qs.created_by,
    qs.payload_json,
    qs.expires_at,
    qs.last_accessed_at,
    qs.created_at,
    u.email,
    u.full_name
FROM query_shares qs
JOIN users u ON u.id = qs.created_by
WHERE qs.token = $1
`

type GetQueryShareRow struct {
	Token          string             `json:"token"`
	SourceID       int64              `json:"source_id"`
	TeamID         pgtype.Int8        `json:"team_id"`
	CreatedBy      int64              `json:"created_by"`
	PayloadJson    string             `json:"payload_json"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Email          string             `json:"email"`
	FullName       string             `json:"full_name"`
}

// Retrieve an ad hoc query share by token with creator details
func (q *Queries) GetQueryShare(ctx context.Context, token string) (GetQueryShareRow, error) {
	row := q.db.QueryRow(ctx, getQueryShare, token)
	var i GetQueryShareRow
	err := row.Scan(
		&i.Token,
		&i.SourceID,
		&i.TeamID,
		&i.CreatedBy,
		&i.PayloadJson,
		&i.ExpiresAt,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const getSavedQuery = `-- name: GetSavedQuery :one
SELECT id, source_id, name, description, query_content, created_by, created_from_team_id, created_at, updated_at, query_language, editor_mode FROM saved_queries WHERE id = $1
`

// Look up one saved query by id
func (q *Queries) GetSavedQuery(ctx context.Context, id int64) (SavedQuery, error) {
	row := q.db.QueryRow(ctx, getSavedQuery, id)
	var i SavedQuery
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.Description,
		&i.QueryContent,
		&i.CreatedBy,
		&i.CreatedFromTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueryLanguage,
		&i.EditorMode,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at FROM sessions WHERE id = $1
`

// Get a session by ID
func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, name, _meta_is_auto_created, _meta_ts_field, _meta_severity_field, description, ttl_days, managed, secret_ref, created_at, updated_at, source_type, connection_config, identity_key FROM sources WHERE id = $1
`

// Get a single source by ID
func (q *Queries) GetSource(ctx context.Context, id int64) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MetaIsAutoCreated,
		&i.MetaTsField,
		&i.MetaSeverityField,
		&i.Description,
		&i.TtlDays,
		&i.Managed,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.ConnectionConfig,
		&i.IdentityKey,
	)
	return i, err
}

const getSourceByIdentityKey = `-- name: GetSourceByIdentityKey :one
SELECT id, name, _meta_is_auto_created, _meta_ts_field, _meta_severity_field, description, ttl_days, managed, secret_ref, created_at, updated_at, source_type, connection_config, identity_key FROM sources WHERE identity_key = $1
`

// Get a single source by provider-computed identity key
func (q *Queries) GetSourceByIdentityKey(ctx context.Context, identityKey string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByIdentityKey, identityKey)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MetaIsAutoCreated,
		&i.MetaTsField,
		&i.MetaSeverityField,
		&i.Description,
		&i.TtlDays,
		&i.Managed,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.ConnectionConfig,
		&i.IdentityKey,
	)
	return i, err
}

const getSourceByNameForProvisioning = `-- name: GetSourceByNameForProvisioning :one
SELECT id, name, _meta_is_auto_created, _meta_ts_field, _meta_severity_field, description, ttl_days, managed, secret_ref, created_at, updated_at, source_type, connection_config, identity_key FROM sources WHERE name = $1
`

// Get source by name for provisioning lookup
func (q *Queries) GetSourceByNameForProvisioning(ctx context.Context, name string) (Source, error) {
	row := q.db.QueryRow(ctx, getSourceByNameForProvisioning, name)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MetaIsAutoCreated,
		&i.MetaTsField,
		&i.MetaSeverityField,
		&i.Description,
		&i.TtlDays,
		&i.Managed,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceType,
		&i.ConnectionConfig,
		&i.IdentityKey,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one

SELECT key, value, value_type, category, description, is_sensitive, created_at, updated_at FROM system_settings
WHERE key = $1
`

// System Settings Queries
func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.Category,
		&i.Description,
		&i.IsSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, description, managed, created_at, updated_at FROM teams WHERE id = $1
`

// Get a team by ID
func (q *Queries) GetTeam(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Managed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, name, description, managed, created_at, updated_at FROM teams WHERE name = $1
`

// Get a team by its name
func (q *Queries) GetTeamByName(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Managed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, role, created_at FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

// Get a team member
func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, full_name, role, status, last_login_at, last_active_at, managed, account_type, created_at, updated_at FROM users WHERE id = $1
`

// Get a user by ID
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.LastActiveAt,
		&i.Managed,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, role, status, last_login_at, last_active_at, managed, account_type, created_at, updated_at FROM users WHERE email = $1
`

// Get a user by email
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.LastActiveAt,
		&i.Managed,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one

SELECT user_id, preferences_json, created_at, updated_at FROM user_preferences WHERE user_id = $1
`

// User Preferences
// Get user preferences by user ID
func (q *Queries) GetUserPreferences(ctx context.Context, userID int64) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.PreferencesJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTeamForSource = `-- name: GetUserTeamForSource :one
SELECT tm.team_id FROM team_members tm
JOIN team_sources ts ON tm.team_id = ts.team_id
WHERE tm.user_id = $1 AND ts.source_id = $2
LIMIT 1
`

type GetUserTeamForSourceParams struct {
	UserID   int64 `json:"user_id"`
	SourceID int64 `json:"source_id"`
}

// Get a team ID that the user belongs to and that has access to the source
func (q *Queries) GetUserTeamForSource(ctx context.Context, arg GetUserTeamForSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserTeamForSource, arg.UserID, arg.SourceID)
	var team_id int64
	err := row.Scan(&team_id)
	return team_id, err
}

const insertAlertHistory = `-- name: InsertAlertHistory :one

INSERT INTO alert_history (
    alert_id,
    status,
    value,
    message,
    payload_json
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, alert_id, status, triggered_at, resolved_at, value, message, payload_json, created_at
`

type InsertAlertHistoryParams struct {
	AlertID     int64         `json:"alert_id"`
	Status      string        `json:"status"`
	Value       pgtype.Float8 `json:"value"`
	Message     pgtype.Text   `json:"message"`
	PayloadJson pgtype.Text   `json:"payload_json"`
}

// Alert history queries
func (q *Queries) InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error) {
	row := q.db.QueryRow(ctx, insertAlertHistory,
		arg.AlertID,
		arg.Status,
		arg.Value,
		arg.Message,
		arg.PayloadJson,
	)
	var i AlertHistory
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Status,
		&i.TriggeredAt,
		&i.ResolvedAt,
		&i.Value,
		&i.Message,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const isSourceManaged = `-- name: IsSourceManaged :one
SELECT managed FROM sources WHERE id = $1
`

// Check if a source is managed
func (q *Queries) IsSourceManaged(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isSourceManaged, id)
	var managed bool
	err := row.Scan(&managed)
	return managed, err
}

const isTeamManaged = `-- name: IsTeamManaged :one
SELECT managed FROM teams WHERE id = $1
`

// Check if a team is managed
func (q *Queries) IsTeamManaged(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamManaged, id)
	var managed bool
	err := row.Scan(&managed)
	return managed, err
}

const isUserManaged = `-- name: IsUserManaged :one
SELECT managed FROM users WHERE id = $1
`

// Check if a user is managed
func (q *Queries) IsUserManaged(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isUserManaged, id)
	var managed bool
	err := row.Scan(&managed)
	return managed, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, name, token_hash, prefix, scopes, last_used_at, expires_at, created_at, updated_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

// List all API tokens for a user
func (q *Queries) ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAlertsDue = `-- name: ListActiveAlertsDue :many
SELECT id, source_id, name, description, query, condition_json, lookback_seconds, threshold_operator, threshold_value, frequency_seconds, severity, labels_json, annotations_json, generator_url, is_active, last_state, last_evaluated_at, last_triggered_at, recipient_user_ids_json, webhook_urls_json, created_by, created_at, updated_at, query_language, editor_mode FROM alerts
WHERE is_active = true
  AND (
        last_evaluated_at IS NULL
        OR last_evaluated_at <= now() - frequency_seconds * interval '1 second'
      )
`

func (q *Queries) ListActiveAlertsDue(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listActiveAlertsDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.ConditionJson,
			&i.LookbackSeconds,
			&i.ThresholdOperator,
			&i.ThresholdValue,
			&i.FrequencySeconds,
			&i.Severity,
			&i.LabelsJson,
			&i.AnnotationsJson,
			&i.GeneratorUrl,
			&i.IsActive,
			&i.LastState,
			&i.LastEvaluatedAt,
			&i.LastTriggeredAt,
			&i.RecipientUserIdsJson,
			&i.WebhookUrlsJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QueryLanguage,
			&i.EditorMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertHistory = `-- name: ListAlertHistory :many
SELECT id, alert_id, status, triggered_at, resolved_at, value, message, payload_json, created_at FROM alert_history
WHERE alert_id = $1
ORDER BY triggered_at DESC, id DESC
LIMIT $2
`

type ListAlertHistoryParams struct {
	AlertID int64 `json:"alert_id"`
	Limit   int32 `json:"limit"`
}

func (q *Queries) ListAlertHistory(ctx context.Context, arg ListAlertHistoryParams) ([]AlertHistory, error) {
	rows, err := q.db.Query(ctx, listAlertHistory, arg.AlertID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertHistory{}
	for rows.Next() {
		var i AlertHistory
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Status,
			&i.TriggeredAt,
			&i.ResolvedAt,
			&i.Value,
			&i.Message,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsBySource = `-- name: ListAlertsBySource :many
SELECT id, source_id, name, description, query, condition_json, lookback_seconds, threshold_operator, threshold_value, frequency_seconds, severity, labels_json, annotations_json, generator_url, is_active, last_state, last_evaluated_at, last_triggered_at, recipient_user_ids_json, webhook_urls_json, created_by, created_at, updated_at, query_language, editor_mode FROM alerts
WHERE source_id = $1
ORDER BY updated_at DESC, created_at DESC
`

// List alerts for one source
func (q *Queries) ListAlertsBySource(ctx context.Context, sourceID int64) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.ConditionJson,
			&i.LookbackSeconds,
			&i.ThresholdOperator,
			&i.ThresholdValue,
			&i.FrequencySeconds,
			&i.Severity,
			&i.LabelsJson,
			&i.AnnotationsJson,
			&i.GeneratorUrl,
			&i.IsActive,
			&i.LastState,
			&i.LastEvaluatedAt,
			&i.LastTriggeredAt,
			&i.RecipientUserIdsJson,
			&i.WebhookUrlsJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QueryLanguage,
			&i.EditorMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsForUser = `-- name: ListAlertsForUser :many
SELECT a.id, a.source_id, a.name, a.description, a.query, a.condition_json, a.lookback_seconds, a.threshold_operator, a.threshold_value, a.frequency_seconds, a.severity, a.labels_json, a.annotations_json, a.generator_url, a.is_active, a.last_state, a.last_evaluated_at, a.last_triggered_at, a.recipient_user_ids_json, a.webhook_urls_json, a.created_by, a.created_at, a.updated_at, a.query_language, a.editor_mode FROM alerts a
WHERE a.source_id IN (
    SELECT DISTINCT ts.source_id
    FROM team_sources ts
    JOIN team_members tm ON tm.team_id = ts.team_id
    WHERE tm.user_id = $1
)
ORDER BY a.updated_at DESC, a.created_at DESC
`

// List every alert the user can see (any source attached to any of their teams)
func (q *Queries) ListAlertsForUser(ctx context.Context, userID int64) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.ConditionJson,
			&i.LookbackSeconds,
			&i.ThresholdOperator,
			&i.ThresholdValue,
			&i.FrequencySeconds,
			&i.Severity,
			&i.LabelsJson,
			&i.AnnotationsJson,
			&i.GeneratorUrl,
			&i.IsActive,
			&i.LastState,
			&i.LastEvaluatedAt,
			&i.LastTriggeredAt,
			&i.RecipientUserIdsJson,
			&i.WebhookUrlsJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QueryLanguage,
			&i.EditorMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSavedQueries = `-- name: ListAllSavedQueries :many
SELECT
    sq.id,
    sq.source_id,
    sq.created_from_team_id,
    sq.name,
    sq.description,
    sq.query_language,
    sq.editor_mode,
    sq.query_content,
    sq.created_at,
    sq.updated_at,
    sq.created_by,
    s.name AS source_name
FROM saved_queries sq
JOIN sources s ON s.id = sq.source_id
ORDER BY sq.updated_at DESC
`

type ListAllSavedQueriesRow struct {
	ID                int64              `json:"id"`
	SourceID          int64              `json:"source_id"`
	CreatedFromTeamID pgtype.Int8        `json:"created_from_team_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	QueryLanguage     string             `json:"query_language"`
	EditorMode        string             `json:"editor_mode"`
	QueryContent      string             `json:"query_content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.Int8        `json:"created_by"`
	SourceName        string             `json:"source_name"`
}

// List every saved query without a source-access gate. This is only for the
// global-admin browse surface; callers must authorize before invoking it.
func (q *Queries) ListAllSavedQueries(ctx context.Context) ([]ListAllSavedQueriesRow, error) {
	rows, err := q.db.Query(ctx, listAllSavedQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSavedQueriesRow{}
	for rows.Next() {
		var i ListAllSavedQueriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.CreatedFromTeamID,
			&i.Name,
			&i.Description,
			&i.QueryLanguage,
			&i.EditorMode,
			&i.QueryContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionItems = `-- name: ListCollectionItems :many
SELECT
    ci.collection_id,
    ci.saved_query_id,
    ci.sort_order,
    ci.added_by,
    ci.created_at AS item_added_at,
    sq.id AS query_id,
    sq.source_id,
    sq.name AS query_name,
    sq.description AS query_description,
    sq.query_language,
    sq.editor_mode,
    sq.query_content,
    sq.created_by AS query_created_by,
    sq.created_at AS query_created_at,
    sq.updated_at AS query_updated_at,
    s.name AS source_name
FROM collection_items ci
JOIN saved_queries sq ON sq.id = ci.saved_query_id
JOIN sources s ON s.id = sq.source_id
WHERE ci.collection_id = $1
ORDER BY ci.sort_order ASC, ci.created_at ASC
`

type ListCollectionItemsRow struct {
	CollectionID     int64              `json:"collection_id"`
	SavedQueryID     int64              `json:"saved_query_id"`
	SortOrder        int64              `json:"sort_order"`
	AddedBy          pgtype.Int8        `json:"added_by"`
	ItemAddedAt      pgtype.Timestamptz `json:"item_added_at"`
	QueryID          int64              `json:"query_id"`
	SourceID         int64              `json:"source_id"`
	QueryName        string             `json:"query_name"`
	QueryDescription pgtype.Text        `json:"query_description"`
	QueryLanguage    string             `json:"query_language"`
	EditorMode       string             `json:"editor_mode"`
	QueryContent     string             `json:"query_content"`
	QueryCreatedBy   pgtype.Int8        `json:"query_created_by"`
	QueryCreatedAt   pgtype.Timestamptz `json:"query_created_at"`
	QueryUpdatedAt   pgtype.Timestamptz `json:"query_updated_at"`
	SourceName       string             `json:"source_name"`
}

// List items in a collection with saved-query details
func (q *Queries) ListCollectionItems(ctx context.Context, collectionID int64) ([]ListCollectionItemsRow, error) {
	rows, err := q.db.Query(ctx, listCollectionItems, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionItemsRow{}
	for rows.Next() {
		var i ListCollectionItemsRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.SavedQueryID,
			&i.SortOrder,
			&i.AddedBy,
			&i.ItemAddedAt,
			&i.QueryID,
			&i.SourceID,
			&i.QueryName,
			&i.QueryDescription,
			&i.QueryLanguage,
			&i.EditorMode,
			&i.QueryContent,
			&i.QueryCreatedBy,
			&i.QueryCreatedAt,
			&i.QueryUpdatedAt,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionMembers = `-- name: ListCollectionMembers :many
SELECT cm.collection_id, cm.user_id, cm.role, cm.added_by, cm.created_at,
       u.email, u.full_name
FROM collection_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.collection_id = $1
ORDER BY cm.role DESC, u.email ASC
`

type ListCollectionMembersRow struct {
	CollectionID int64              `json:"collection_id"`
	UserID       int64              `json:"user_id"`
	Role         string             `json:"role"`
	AddedBy      pgtype.Int8        `json:"added_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
}

// List members of a collection with user details
func (q *Queries) ListCollectionMembers(ctx context.Context, collectionID int64) ([]ListCollectionMembersRow, error) {
	rows, err := q.db.Query(ctx, listCollectionMembers, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionMembersRow{}
	for rows.Next() {
		var i ListCollectionMembersRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.UserID,
			&i.Role,
			&i.AddedBy,
			&i.CreatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsForUser = `-- name: ListCollectionsForUser :many
SELECT
    c.id,
    c.name,
    c.description,
    c.is_personal,
    c.created_by,
    c.created_at,
    c.updated_at,
    cm.role AS caller_role,
    (SELECT COUNT(*) FROM collection_members WHERE collection_id = c.id) AS member_count,
    (SELECT COUNT(*) FROM collection_items WHERE collection_id = c.id) AS item_count
FROM collections c
JOIN collection_members cm ON cm.collection_id = c.id
WHERE cm.user_id = $1
ORDER BY c.is_personal DESC, c.updated_at DESC
`

type ListCollectionsForUserRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsPersonal  bool               `json:"is_personal"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CallerRole  string             `json:"caller_role"`
	MemberCount int64              `json:"member_count"`
	ItemCount   int64              `json:"item_count"`
}

// List collections the user owns or is a member of, with member count and item count
func (q *Queries) ListCollectionsForUser(ctx context.Context, userID int64) ([]ListCollectionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCollectionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsForUserRow{}
	for rows.Next() {
		var i ListCollectionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPersonal,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CallerRole,
			&i.MemberCount,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredExportJobPaths = `-- name: ListExpiredExportJobPaths :many
SELECT file_path
FROM export_jobs
WHERE expires_at < $1
  AND file_path IS NOT NULL
`

// List artifact paths for expired export jobs
func (q *Queries) ListExpiredExportJobPaths(ctx context.Context, expiresAt pgtype.Timestamptz) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listExpiredExportJobPaths, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var file_path pgtype.Text
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedSources = `-- name: ListManagedSources :many

SELECT id, name, _meta_is_auto_created, _meta_ts_field, _meta_severity_field, description, ttl_days, managed, secret_ref, created_at, updated_at, source_type, connection_config, identity_key FROM sources WHERE managed = true ORDER BY id
`

// Provisioning Queries
// Get all sources managed by provisioning config
func (q *Queries) ListManagedSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listManagedSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MetaIsAutoCreated,
			&i.MetaTsField,
			&i.MetaSeverityField,
			&i.Description,
			&i.TtlDays,
			&i.Managed,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.ConnectionConfig,
			&i.IdentityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedTeams = `-- name: ListManagedTeams :many
SELECT id, name, description, managed, created_at, updated_at FROM teams WHERE managed = true ORDER BY id
`

// Get all teams managed by provisioning config
func (q *Queries) ListManagedTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listManagedTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Managed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT id, email, full_name, role, status, last_login_at, last_active_at, managed, account_type, created_at, updated_at FROM users WHERE managed = true ORDER BY id
`

// Get all users managed by provisioning config
func (q *Queries) ListManagedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listManagedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.LastActiveAt,
			&i.Managed,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedQueriesForUser = `-- name: ListSavedQueriesForUser :many
SELECT
    sq.id,
    sq.source_id,
    sq.created_from_team_id,
    sq.name,
    sq.description,
    sq.query_language,
    sq.editor_mode,
    sq.query_content,
    sq.created_at,
    sq.updated_at,
    sq.created_by,
    s.name AS source_name
FROM saved_queries sq
JOIN sources s ON s.id = sq.source_id
WHERE sq.source_id IN (
    SELECT DISTINCT ts.source_id
    FROM team_sources ts
    JOIN team_members tm ON tm.team_id = ts.team_id
    WHERE tm.user_id = $1
)
ORDER BY sq.updated_at DESC
`

type ListSavedQueriesForUserRow struct {
	ID                int64              `json:"id"`
	SourceID          int64              `json:"source_id"`
	CreatedFromTeamID pgtype.Int8        `json:"created_from_team_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	QueryLanguage     string             `json:"query_language"`
	EditorMode        string             `json:"editor_mode"`
	QueryContent      string             `json:"query_content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.Int8        `json:"created_by"`
	SourceName        string             `json:"source_name"`
}

// List every saved query the user can see (any source attached to any of their teams)
func (q *Queries) ListSavedQueriesForUser(ctx context.Context, userID int64) ([]ListSavedQueriesForUserRow, error) {
	rows, err := q.db.Query(ctx, listSavedQueriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedQueriesForUserRow{}
	for rows.Next() {
		var i ListSavedQueriesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.CreatedFromTeamID,
			&i.Name,
			&i.Description,
			&i.QueryLanguage,
			&i.EditorMode,
			&i.QueryContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedQueriesForUserBySource = `-- name: ListSavedQueriesForUserBySource :many
SELECT
    sq.id,
    sq.source_id,
    sq.created_from_team_id,
    sq.name,
    sq.description,
    sq.query_language,
    sq.editor_mode,
    sq.query_content,
    sq.created_at,
    sq.updated_at,
    sq.created_by,
    s.name AS source_name
FROM saved_queries sq
JOIN sources s ON s.id = sq.source_id
WHERE sq.source_id = $1
  AND EXISTS (
    SELECT 1 FROM team_sources ts
    JOIN team_members tm ON tm.team_id = ts.team_id
    WHERE ts.source_id = sq.source_id AND tm.user_id = $2
  )
ORDER BY sq.updated_at DESC
`

type ListSavedQueriesForUserBySourceParams struct {
	SourceID int64 `json:"source_id"`
	UserID   int64 `json:"user_id"`
}

type ListSavedQueriesForUserBySourceRow struct {
	ID                int64              `json:"id"`
	SourceID          int64              `json:"source_id"`
	CreatedFromTeamID pgtype.Int8        `json:"created_from_team_id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	QueryLanguage     string             `json:"query_language"`
	EditorMode        string             `json:"editor_mode"`
	QueryContent      string             `json:"query_content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedBy         pgtype.Int8        `json:"created_by"`
	SourceName        string             `json:"source_name"`
}

// List saved queries for a specific source, scoped to a user that has access to it
func (q *Queries) ListSavedQueriesForUserBySource(ctx context.Context, arg ListSavedQueriesForUserBySourceParams) ([]ListSavedQueriesForUserBySourceRow, error) {
	rows, err := q.db.Query(ctx, listSavedQueriesForUserBySource, arg.SourceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedQueriesForUserBySourceRow{}
	for rows.Next() {
		var i ListSavedQueriesForUserBySourceRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.CreatedFromTeamID,
			&i.Name,
			&i.Description,
			&i.QueryLanguage,
			&i.EditorMode,
			&i.QueryContent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccounts = `-- name: ListServiceAccounts :many
SELECT id, email, full_name, role, status, last_login_at, last_active_at, managed, account_type, created_at, updated_at FROM users WHERE account_type = 'service' ORDER BY created_at ASC
`

// List service principals
func (q *Queries) ListServiceAccounts(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listServiceAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.LastActiveAt,
			&i.Managed,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceTeams = `-- name: ListSourceTeams :many
SELECT t.id, t.name, t.description, t.managed, t.created_at, t.updated_at
FROM teams t
JOIN team_sources ts ON t.id = ts.team_id
WHERE ts.source_id = $1
ORDER BY t.name
`

// List all teams a data source is a member of
func (q *Queries) ListSourceTeams(ctx context.Context, sourceID int64) ([]Team, error) {
	rows, err := q.db.Query(ctx, listSourceTeams, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Managed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, name, _meta_is_auto_created, _meta_ts_field, _meta_severity_field, description, ttl_days, managed, secret_ref, created_at, updated_at, source_type, connection_config, identity_key FROM sources ORDER BY created_at DESC
`

// Get all sources ordered by creation date
func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MetaIsAutoCreated,
			&i.MetaTsField,
			&i.MetaSeverityField,
			&i.Description,
			&i.TtlDays,
			&i.Managed,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.ConnectionConfig,
			&i.IdentityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourcesForUser = `-- name: ListSourcesForUser :many
SELECT DISTINCT s.id, s.name, s._meta_is_auto_created, s._meta_ts_field, s._meta_severity_field, s.description, s.ttl_days, s.managed, s.secret_ref, s.created_at, s.updated_at, s.source_type, s.connection_config, s.identity_key FROM sources s
JOIN team_sources ts ON s.id = ts.source_id
JOIN team_members tm ON ts.team_id = tm.team_id
WHERE tm.user_id = $1
ORDER BY s.created_at DESC
`

// List all sources a user has access to
func (q *Queries) ListSourcesForUser(ctx context.Context, userID int64) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MetaIsAutoCreated,
			&i.MetaTsField,
			&i.MetaSeverityField,
			&i.Description,
			&i.TtlDays,
			&i.Managed,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.ConnectionConfig,
			&i.IdentityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, value_type, category, description, is_sensitive, created_at, updated_at FROM system_settings
ORDER BY category, key
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.Category,
			&i.Description,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettingsByCategory = `-- name: ListSystemSettingsByCategory :many
SELECT key, value, value_type, category, description, is_sensitive, created_at, updated_at FROM system_settings
WHERE category = $1
ORDER BY key
`

func (q *Queries) ListSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.Category,
			&i.Description,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.team_id, tm.user_id, tm.role, tm.created_at
FROM team_members tm
WHERE tm.team_id = $1
ORDER BY tm.created_at
`

// List all members of a team
func (q *Queries) ListTeamMembers(ctx context.Context, teamID int64) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMember{}
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembersWithDetails = `-- name: ListTeamMembersWithDetails :many
SELECT tm.team_id, tm.user_id, tm.role, tm.created_at, u.email, u.full_name, u.account_type
FROM team_members tm
JOIN users u ON tm.user_id = u.id
WHERE tm.team_id = $1
ORDER BY tm.created_at ASC
`

type ListTeamMembersWithDetailsRow struct {
	TeamID      int64              `json:"team_id"`
	UserID      int64              `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	FullName    string             `json:"full_name"`
	AccountType string             `json:"account_type"`
}

// List all members of a team with user details
func (q *Queries) ListTeamMembersWithDetails(ctx context.Context, teamID int64) ([]ListTeamMembersWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembersWithDetails, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersWithDetailsRow{}
	for rows.Next() {
		var i ListTeamMembersWithDetailsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.FullName,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamSources = `-- name: ListTeamSources :many
SELECT s.id, s.name, s._meta_is_auto_created, s._meta_ts_field, s._meta_severity_field, s.description, s.ttl_days, s.managed, s.secret_ref, s.created_at, s.updated_at, s.source_type, s.connection_config, s.identity_key
FROM sources s
JOIN team_sources ts ON s.id = ts.source_id
WHERE ts.team_id = $1
ORDER BY s.created_at DESC
`

// List all data sources in a team
func (q *Queries) ListTeamSources(ctx context.Context, teamID int64) ([]Source, error) {
	rows, err := q.db.Query(ctx, listTeamSources, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MetaIsAutoCreated,
			&i.MetaTsField,
			&i.MetaSeverityField,
			&i.Description,
			&i.TtlDays,
			&i.Managed,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceType,
			&i.ConnectionConfig,
			&i.IdentityKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.name, t.description, t.managed, t.created_at, t.updated_at, COUNT(tm.user_id) as member_count
FROM teams t
LEFT JOIN team_members tm ON t.id = tm.team_id
GROUP BY t.id
ORDER BY t.created_at DESC
`

type ListTeamsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Managed     bool               `json:"managed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberCount int64              `json:"member_count"`
}

// List all teams
func (q *Queries) ListTeams(ctx context.Context) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Managed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT
    t.id,
    t.name,
    t.description,
    t.created_at,
    t.updated_at,
    tm.role,  -- The current user's role in this team
    (SELECT COUNT(*) FROM team_members sub_tm WHERE sub_tm.team_id = t.id) as member_count
FROM
    teams t
JOIN
    team_members tm ON t.id = tm.team_id
WHERE
    tm.user_id = $1  -- The current user ID
ORDER BY
    t.created_at DESC
`

type ListTeamsForUserRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Role        string             `json:"role"`
	MemberCount int64              `json:"member_count"`
}

// List all teams a user is a member of
func (q *Queries) ListTeamsForUser(ctx context.Context, userID int64) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserRow{}
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, t.description, t.managed, t.created_at, t.updated_at
FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1
ORDER BY t.name
`

// List all teams a user is a member of
func (q *Queries) ListUserTeams(ctx context.Context, userID int64) ([]Team, error) {
	rows, err := q.db.Query(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Managed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, full_name, role, status, last_login_at, last_active_at, managed, account_type, created_at, updated_at FROM users ORDER BY created_at ASC
`

// List all users
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.LastActiveAt,
			&i.Managed,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertEvaluated = `-- name: MarkAlertEvaluated :exec
UPDATE alerts
SET last_state = 'resolved',
    last_evaluated_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkAlertEvaluated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAlertEvaluated, id)
	return err
}

const markAlertTriggered = `-- name: MarkAlertTriggered :exec
UPDATE alerts
SET last_state = 'firing',
    last_triggered_at = CASE WHEN last_state = 'firing' THEN last_triggered_at ELSE now() END,
    last_evaluated_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkAlertTriggered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAlertTriggered, id)
	return err
}

const pruneAlertHistory = `-- name: PruneAlertHistory :exec
DELETE FROM alert_history AS target
WHERE target.alert_id = $1
  AND target.id NOT IN (
    SELECT keep.id
    FROM alert_history AS keep
    WHERE keep.alert_id = $2
    ORDER BY keep.triggered_at DESC, keep.id DESC
    LIMIT $3
 )
`

type PruneAlertHistoryParams struct {
	AlertID   int64 `json:"alert_id"`
	AlertID_2 int64 `json:"alert_id_2"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) PruneAlertHistory(ctx context.Context, arg PruneAlertHistoryParams) error {
	_, err := q.db.Exec(ctx, pruneAlertHistory, arg.AlertID, arg.AlertID_2, arg.Limit)
	return err
}

const pruneExpiredQueryShares = `-- name: PruneExpiredQueryShares :exec
DELETE FROM query_shares
WHERE expires_at < $1
`

// Delete expired query shares
func (q *Queries) PruneExpiredQueryShares(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, pruneExpiredQueryShares, expiresAt)
	return err
}

const removeCollectionItem = `-- name: RemoveCollectionItem :exec
DELETE FROM collection_items WHERE collection_id = $1 AND saved_query_id = $2
`

type RemoveCollectionItemParams struct {
	CollectionID int64 `json:"collection_id"`
	SavedQueryID int64 `json:"saved_query_id"`
}

// Remove an item from a collection
func (q *Queries) RemoveCollectionItem(ctx context.Context, arg RemoveCollectionItemParams) error {
	_, err := q.db.Exec(ctx, removeCollectionItem, arg.CollectionID, arg.SavedQueryID)
	return err
}

const removeCollectionMember = `-- name: RemoveCollectionMember :exec
DELETE FROM collection_members WHERE collection_id = $1 AND user_id = $2
`

type RemoveCollectionMemberParams struct {
	CollectionID int64 `json:"collection_id"`
	UserID       int64 `json:"user_id"`
}

// Remove a member from a collection
func (q *Queries) RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) error {
	_, err := q.db.Exec(ctx, removeCollectionMember, arg.CollectionID, arg.UserID)
	return err
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID int64 `json:"team_id"`
	UserID int64 `json:"user_id"`
}

// Remove a member from a team
func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const removeTeamSource = `-- name: RemoveTeamSource :exec
DELETE FROM team_sources WHERE team_id = $1 AND source_id = $2
`

type RemoveTeamSourceParams struct {
	TeamID   int64 `json:"team_id"`
	SourceID int64 `json:"source_id"`
}

// Remove a data source from a team
func (q *Queries) RemoveTeamSource(ctx context.Context, arg RemoveTeamSourceParams) error {
	_, err := q.db.Exec(ctx, removeTeamSource, arg.TeamID, arg.SourceID)
	return err
}

const resolveAlertHistory = `-- name: ResolveAlertHistory :one
UPDATE alert_history
SET status = 'resolved',
    resolved_at = now(),
    message = $1
WHERE id = $2
RETURNING id
`

type ResolveAlertHistoryParams struct {
	Message pgtype.Text `json:"message"`
	ID      int64       `json:"id"`
}

func (q *Queries) ResolveAlertHistory(ctx context.Context, arg ResolveAlertHistoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveAlertHistory, arg.Message, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setSourceManaged = `-- name: SetSourceManaged :exec
UPDATE sources SET managed = $1, secret_ref = $2, updated_at = now() WHERE id = $3
`

type SetSourceManagedParams struct {
	Managed   bool        `json:"managed"`
	SecretRef pgtype.Text `json:"secret_ref"`
	ID        int64       `json:"id"`
}

// Mark a source as managed/unmanaged and set secret_ref
func (q *Queries) SetSourceManaged(ctx context.Context, arg SetSourceManagedParams) error {
	_, err := q.db.Exec(ctx, setSourceManaged, arg.Managed, arg.SecretRef, arg.ID)
	return err
}

const setTeamManaged = `-- name: SetTeamManaged :exec
UPDATE teams SET managed = $1, updated_at = now() WHERE id = $2
`

type SetTeamManagedParams struct {
	Managed bool  `json:"managed"`
	ID      int64 `json:"id"`
}

// Mark a team as managed/unmanaged
func (q *Queries) SetTeamManaged(ctx context.Context, arg SetTeamManagedParams) error {
	_, err := q.db.Exec(ctx, setTeamManaged, arg.Managed, arg.ID)
	return err
}

const setUserManaged = `-- name: SetUserManaged :exec
UPDATE users SET managed = $1, updated_at = now() WHERE id = $2
`

type SetUserManagedParams struct {
	Managed bool  `json:"managed"`
	ID      int64 `json:"id"`
}

// Mark a user as managed/unmanaged
func (q *Queries) SetUserManaged(ctx context.Context, arg SetUserManagedParams) error {
	_, err := q.db.Exec(ctx, setUserManaged, arg.Managed, arg.ID)
	return err
}

const teamHasSource = `-- name: TeamHasSource :one

SELECT EXISTS(
    SELECT 1 FROM team_sources
    WHERE team_id = $1 AND source_id = $2
)
`

type TeamHasSourceParams struct {
	TeamID   int64 `json:"team_id"`
	SourceID int64 `json:"source_id"`
}

// Additional queries for user-source and team-source access
// Check if a team has access to a source
func (q *Queries) TeamHasSource(ctx context.Context, arg TeamHasSourceParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamHasSource, arg.TeamID, arg.SourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchQueryShare = `-- name: TouchQueryShare :exec
UPDATE query_shares
SET last_accessed_at = $1
WHERE token = $2
`

type TouchQueryShareParams struct {
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	Token          string             `json:"token"`
}

// Update a query share's last access time
func (q *Queries) TouchQueryShare(ctx context.Context, arg TouchQueryShareParams) error {
	_, err := q.db.Exec(ctx, touchQueryShare, arg.LastAccessedAt, arg.Token)
	return err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = now(),
    updated_at = now()
WHERE id = $1
`

// Update the last used timestamp for an API token
func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, id)
	return err
}

const updateAlert = `-- name: UpdateAlert :one
UPDATE alerts
SET name = $1,
    description = $2,
    query_language = $3,
    editor_mode = $4,
    query = $5,
    condition_json = $6,
    lookback_seconds = $7,
    threshold_operator = $8,
    threshold_value = $9,
    frequency_seconds = $10,
    severity = $11,
    labels_json = $12,
    annotations_json = $13,
    recipient_user_ids_json = $14,
    webhook_urls_json = $15,
    generator_url = $16,
    is_active = $17,
    updated_at = now()
WHERE id = $18
RETURNING id
`

type UpdateAlertParams struct {
	Name                 string      `json:"name"`
	Description          pgtype.Text `json:"description"`
	QueryLanguage        string      `json:"query_language"`
	EditorMode           string      `json:"editor_mode"`
	Query                pgtype.Text `json:"query"`
	ConditionJson        pgtype.Text `json:"condition_json"`
	LookbackSeconds      int64       `json:"lookback_seconds"`
	ThresholdOperator    string      `json:"threshold_operator"`
	ThresholdValue       float64     `json:"threshold_value"`
	FrequencySeconds     int64       `json:"frequency_seconds"`
	Severity             string      `json:"severity"`
	LabelsJson           pgtype.Text `json:"labels_json"`
	AnnotationsJson      pgtype.Text `json:"annotations_json"`
	RecipientUserIdsJson pgtype.Text `json:"recipient_user_ids_json"`
	WebhookUrlsJson      pgtype.Text `json:"webhook_urls_json"`
	GeneratorUrl         pgtype.Text `json:"generator_url"`
	IsActive             bool        `json:"is_active"`
	ID                   int64       `json:"id"`
}

func (q *Queries) UpdateAlert(ctx context.Context, arg UpdateAlertParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateAlert,
		arg.Name,
		arg.Description,
		arg.QueryLanguage,
		arg.EditorMode,
		arg.Query,
		arg.ConditionJson,
		arg.LookbackSeconds,
		arg.ThresholdOperator,
		arg.ThresholdValue,
		arg.FrequencySeconds,
		arg.Severity,
		arg.LabelsJson,
		arg.AnnotationsJson,
		arg.RecipientUserIdsJson,
		arg.WebhookUrlsJson,
		arg.GeneratorUrl,
		arg.IsActive,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateAlertHistoryPayload = `-- name: UpdateAlertHistoryPayload :one
UPDATE alert_history
SET payload_json = $1
WHERE id = $2
RETURNING id
`

type UpdateAlertHistoryPayloadParams struct {
	PayloadJson pgtype.Text `json:"payload_json"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateAlertHistoryPayload(ctx context.Context, arg UpdateAlertHistoryPayloadParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateAlertHistoryPayload, arg.PayloadJson, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections
SET name = $1,
    description = $2,
    updated_at = now()
WHERE id = $3
`

type UpdateCollectionParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          int64       `json:"id"`
}

// Update name/description (owner only - enforced in app code)
func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.Exec(ctx, updateCollection, arg.Name, arg.Description, arg.ID)
	return err
}

const updateExportJobRunning = `-- name: UpdateExportJobRunning :one
UPDATE export_jobs
SET
    status = $1,
    error_message = NULL,
    updated_at = $2
WHERE id = $3
RETURNING id
`

type UpdateExportJobRunningParams struct {
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

// Mark an export job as running and return its ID
func (q *Queries) UpdateExportJobRunning(ctx context.Context, arg UpdateExportJobRunningParams) (string, error) {
	row := q.db.QueryRow(ctx, updateExportJobRunning, arg.Status, arg.UpdatedAt, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateSavedQuery = `-- name: UpdateSavedQuery :exec
UPDATE saved_queries
SET name = $1,
    description = $2,
    query_language = $3,
    editor_mode = $4,
    query_content = $5,
    updated_at = now()
WHERE id = $6
`

type UpdateSavedQueryParams struct {
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	QueryLanguage string      `json:"query_language"`
	EditorMode    string      `json:"editor_mode"`
	QueryContent  string      `json:"query_content"`
	ID            int64       `json:"id"`
}

// Update a saved query's mutable fields
func (q *Queries) UpdateSavedQuery(ctx context.Context, arg UpdateSavedQueryParams) error {
	_, err := q.db.Exec(ctx, updateSavedQuery,
		arg.Name,
		arg.Description,
		arg.QueryLanguage,
		arg.EditorMode,
		arg.QueryContent,
		arg.ID,
	)
	return err
}

const updateSource = `-- name: UpdateSource :exec
UPDATE sources
SET name = $1,
    _meta_is_auto_created = $2,
    source_type = $3,
    _meta_ts_field = $4,
    _meta_severity_field = $5,
    connection_config = $6,
    identity_key = $7,
    description = $8,
    ttl_days = $9,
    managed = $10,
    secret_ref = $11,
    updated_at = now()
WHERE id = $12
`

type UpdateSourceParams struct {
	Name              string      `json:"name"`
	MetaIsAutoCreated bool        `json:"_meta_is_auto_created"`
	SourceType        string      `json:"source_type"`
	MetaTsField       string      `json:"_meta_ts_field"`
	MetaSeverityField pgtype.Text `json:"_meta_severity_field"`
	ConnectionConfig  []byte      `json:"connection_config"`
	IdentityKey       string      `json:"identity_key"`
	Description       pgtype.Text `json:"description"`
	TtlDays           int64       `json:"ttl_days"`
	Managed           bool        `json:"managed"`
	SecretRef         pgtype.Text `json:"secret_ref"`
	ID                int64       `json:"id"`
}

// Update an existing source
func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) error {
	_, err := q.db.Exec(ctx, updateSource,
		arg.Name,
		arg.MetaIsAutoCreated,
		arg.SourceType,
		arg.MetaTsField,
		arg.MetaSeverityField,
		arg.ConnectionConfig,
		arg.IdentityKey,
		arg.Description,
		arg.TtlDays,
		arg.Managed,
		arg.SecretRef,
		arg.ID,
	)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams
SET name = $1,
    description = $2,
    updated_at = $3
WHERE id = $4
`

type UpdateTeamParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int64              `json:"id"`
}

// Update a team
func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.Exec(ctx, updateTeam,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :exec
UPDATE team_members
SET role = $1
WHERE team_id = $2 AND user_id = $3
`

type UpdateTeamMemberRoleParams struct {
	Role   string `json:"role"`
	TeamID int64  `json:"team_id"`
	UserID int64  `json:"user_id"`
}

// Update a team member's role
func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateTeamMemberRole, arg.Role, arg.TeamID, arg.UserID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $1,
    full_name = $2,
    role = $3,
    status = $4,
    last_login_at = $5,
    last_active_at = $6,
    updated_at = $7
WHERE id = $8
`

type UpdateUserParams struct {
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           int64              `json:"id"`
}

// Update a user
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.Status,
		arg.LastLoginAt,
		arg.LastActiveAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value, value_type, category, description, is_sensitive, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    value_type = excluded.value_type,
    description = excluded.description,
    is_sensitive = excluded.is_sensitive,
    updated_at = now()
`

type UpsertSystemSettingParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	ValueType   string      `json:"value_type"`
	Category    string      `json:"category"`
	Description pgtype.Text `json:"description"`
	IsSensitive bool        `json:"is_sensitive"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSystemSetting,
		arg.Key,
		arg.Value,
		arg.ValueType,
		arg.Category,
		arg.Description,
		arg.IsSensitive,
	)
	return err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (user_id, preferences_json, created_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT(user_id) DO UPDATE SET
    preferences_json = excluded.preferences_json,
    updated_at = now()
`

type UpsertUserPreferencesParams struct {
	UserID          int64  `json:"user_id"`
	PreferencesJson string `json:"preferences_json"`
}

// Insert or update user preferences
func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertUserPreferences, arg.UserID, arg.PreferencesJson)
	return err
}

const userHasSourceAccess = `-- name: UserHasSourceAccess :one
SELECT EXISTS(
    SELECT 1 FROM team_members tm
    JOIN team_sources ts ON tm.team_id = ts.team_id
    WHERE tm.user_id = $1 AND ts.source_id = $2
)
`

type UserHasSourceAccessParams struct {
	UserID   int64 `json:"user_id"`
	SourceID int64 `json:"source_id"`
}

// Check if a user has access to a source through any team
func (q *Queries) UserHasSourceAccess(ctx context.Context, arg UserHasSourceAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasSourceAccess, arg.UserID, arg.SourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
