services:
    clickhouse:
        image: clickhouse/clickhouse-server:24.8.4
        user: '101:101'
        container_name: clickhouse
        hostname: clickhouse
        restart: on-failure
        ports:
            - '0.0.0.0:8123:8123'
            - '0.0.0.0:9000:9000'
        volumes:
            - ./config.xml:/etc/clickhouse-server/config.d/logchef.xml
            - ./users.xml:/etc/clickhouse-server/users.d/logchef.xml
            - clickhouse-data:/var/lib/clickhouse
            - clickhouse-logs:/var/log/clickhouse-server
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
        cap_add:
            - SYS_NICE
            - IPC_LOCK


volumes:
    clickhouse-data:
    clickhouse-logs:
