package ai

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"regexp"
	"strings"
	"time"

	clickhouseparser "github.com/AfterShip/clickhouse-sql-parser/parser"

	"github.com/mr-karan/logchef/internal/logchefql"
)

// ErrInvalidSQLGeneratedByAI is returned when the query generated by AI is not
// valid for its target language. It stays the terminal error for all targets.
var ErrInvalidSQLGeneratedByAI = errors.New("AI generated invalid SQL syntax")

// Regular expressions to match markdown code blocks
// Matches a fenced code block with an optional language tag (```sql, ```logsql,
// ```logchefql, or a bare ```), capturing the inner content. The [a-zA-Z]* after
// the fence consumes ANY language tag so it never leaks into the query — the
// LogsQL target has no parser to catch a leaked tag.
var codeBlockRegex = regexp.MustCompile("(?s)```[a-zA-Z]*\\s*(.*?)```")

// TargetLanguage is the concrete query language the Generator emits. The server
// chooses the target deterministically from the source backend and editor mode;
// the model never chooses the backend.
type TargetLanguage string

const (
	TargetClickHouseSQL TargetLanguage = "clickhouse-sql"
	TargetLogchefQL     TargetLanguage = "logchefql"
	TargetLogsQL        TargetLanguage = "logsql"
)

const (
	DefaultMaxTokens               = 1024
	DefaultTemperature             = float32(0.1)
	DefaultTimeout                 = 15 * time.Second // Used for both HTTP client and individual call fallback
	DefaultSystemPromptTableFormat = `You are an expert ClickHouse SQL query assistant for log analytics. Given a table schema and a natural language query, generate an optimized and correct ClickHouse SQL query. Important guidelines:

1. Only use columns present in the provided schema.
2. The table name to query is: %s
3. Always include the table name in the FROM clause.
4. Include proper time range filters if the user is asking about specific time periods.
5. When aggregating data, use ClickHouse-specific functions.
6. ALWAYS include a LIMIT clause with a reasonable limit (use LIMIT 100 by default if not specified).
7. For timestamp fields, use toDateTime functions with timezone support like: toDateTime('2025-05-14 15:00:10', 'Asia/Kolkata')
8. For pattern matching:
   - Use positionCaseInsensitive(column, 'pattern') > 0 when the user wants to find content containing a substring (e.g., "contains", "includes", "has")
   - Use = or equals for exact matches (e.g., "equals", "is", "matches exactly")
   - Use LIKE for simple wildcard patterns, but prefer positionCaseInsensitive for most substring searches
9. Order results by timestamp DESC for log analytics queries unless specified otherwise
10. Output ONLY the executable SQL query - NO code fences, NO markdown formatting, NO explanation.
11. Provide ONLY the raw SQL query itself with no additional formatting or markup.

Example query patterns:
SELECT *
FROM default.logs
WHERE timestamp BETWEEN toDateTime('2025-05-14 15:00:10', 'Asia/Kolkata') AND toDateTime('2025-05-14 15:30:10', 'Asia/Kolkata') AND (positionCaseInsensitive(namespace, 'helo') > 0)
ORDER BY timestamp DESC
LIMIT 100

Provided schema:
%s`

	// LogchefQLSystemPromptFormat teaches LogchefQL, Logchef's shared quick-filter
	// language. It is a filter expression, NOT SQL. Grounded in
	// internal/logchefql (grammar.go / logchefql.go) and the search-syntax docs.
	LogchefQLSystemPromptFormat = `You are an expert LogchefQL query assistant for log analytics. LogchefQL is Logchef's simple filter language: it filters log lines and is NOT SQL. Given a table schema and a natural language query, produce a single valid LogchefQL filter expression. Important guidelines:

1. Only reference fields present in the provided schema.
2. LogchefQL is a FILTER expression, not SQL. NEVER emit SELECT/FROM/WHERE/ORDER BY/LIMIT, semicolons, or SQL functions.
3. A basic term is field=value. Quote string values with double quotes (level="error"); numbers are bare (status=200).
4. Operators:
   - "=" equals, "!=" not equals
   - "~" contains (case-insensitive substring), "!~" does not contain
   - ">", ">=", "<", "<=" numeric comparisons
5. Combine conditions with "and" / "or" (case-insensitive). Group with parentheses, e.g. (service="auth" or service="users") and level="error".
6. Access nested fields with dot notation (log_attributes.user_id="123"). Quote a segment containing special characters (log_attributes."user.name"="alice").
7. Do NOT express a time range: Logchef applies the selected time range separately.
8. Output ONLY the raw LogchefQL expression: NO code fences, NO markdown, NO SQL, NO explanation.

Example query patterns:
level="error" and service="payment-api"
response_time>1000 and status>=500
message~"timeout"

Provided schema:
%s`

	// LogsQLSystemPromptFormat teaches VictoriaLogs LogsQL. Grounded in the
	// logsql-queries docs and internal/logchefql/logsql_generator.go, which
	// shows the LogsQL shapes Logchef expects (field:=value, NOT, :~ regex,
	// numeric colon comparisons, "| fields", "| stats").
	LogsQLSystemPromptFormat = `You are an expert VictoriaLogs LogsQL query assistant for log analytics. Given a table schema and a natural language query, produce a single valid LogsQL query. Important guidelines:

1. Only reference fields present in the provided schema.
2. Exact field match uses a colon: field:="value". Negate with NOT, e.g. NOT level:="error".
3. Substring/regex match uses ":~", e.g. _msg:~"(?i)timeout". Numeric comparisons use a colon: status_code:>=500, response_time_ms:>1000.
4. Combine filters with AND / OR and group with parentheses: (service:="api" OR service:="gateway") AND level:="error".
5. Project fields with a pipe: service:="api" | fields _time, _msg, service, status_code.
6. Aggregate with the stats pipe: service:="payments" level:="error" | stats count() as value.
7. Quote reserved field names or names with special characters, e.g. "field.name":="x". A bare field token must not collide with a LogsQL keyword, pipe, or function name.
8. Do NOT add your own _time: filter: Logchef applies the selected time range separately via start/end.
9. Output ONLY the raw LogsQL query: NO code fences, NO markdown, NO explanation.

Example query patterns:
service:="payments" AND level:="error"
service:="api" AND status_code:>=500
level:="error" | stats count() as value

Provided schema:
%s`
)

// GeneratorConfig contains the model/inference settings for a Generator.
type GeneratorConfig struct {
	Model       string
	MaxTokens   int
	Temperature float32
	Timeout     time.Duration // Timeout applied to an individual GenerateSQL call.
}

// Generator turns natural language into validated ClickHouse SQL. It is
// provider-agnostic: it owns the prompt building, markdown stripping, and
// ClickHouse-parser validation, and delegates the raw text completion to a
// Provider transport.
type Generator struct {
	provider    Provider
	logger      *slog.Logger
	model       string
	maxTokens   int
	temperature float32
	callTimeout time.Duration // Timeout for individual GenerateSQL calls
}

// NewGenerator creates a Generator wrapping the given Provider. Defaults mirror
// the previous single-provider client so existing behavior is preserved.
func NewGenerator(provider Provider, cfg GeneratorConfig, logger *slog.Logger) *Generator {
	model := cfg.Model
	if model == "" {
		model = DefaultOpenAIModel
	}
	maxTokens := cfg.MaxTokens
	if maxTokens == 0 {
		maxTokens = DefaultMaxTokens
	}
	temperature := cfg.Temperature
	if temperature == 0 {
		temperature = DefaultTemperature
	}
	callTimeout := cfg.Timeout
	if callTimeout == 0 {
		callTimeout = DefaultTimeout
	}

	return &Generator{
		provider:    provider,
		logger:      logger.With("component", "ai_generator"),
		model:       model,
		maxTokens:   maxTokens,
		temperature: temperature,
		callTimeout: callTimeout,
	}
}

// GenerateQueryInput is the request for GenerateQuery. Target fixes the concrete
// language emitted (chosen server-side); the other fields carry the natural
// language ask, schema, table name, and optional current-query context.
type GenerateQueryInput struct {
	Target               TargetLanguage
	NaturalLanguageQuery string
	Schema               string
	TableName            string
	CurrentQuery         string // Optional current query for context
}

// GenerateSQL generates a ClickHouse SQL query from a natural language query and
// schema. It is a thin wrapper over GenerateQuery pinned to the ClickHouse-SQL
// target, preserving the exact prompt and validation behavior of the pre-P2
// single-target client.
func (g *Generator) GenerateSQL(
	ctx context.Context,
	naturalLanguageQuery string,
	schema string,
	tableName string,
	currentQuery string, // Optional current query for context
) (string, error) {
	return g.GenerateQuery(ctx, GenerateQueryInput{
		Target:               TargetClickHouseSQL,
		NaturalLanguageQuery: naturalLanguageQuery,
		Schema:               schema,
		TableName:            tableName,
		CurrentQuery:         currentQuery,
	})
}

// GenerateQuery turns natural language into a validated query in the requested
// target language. It builds a per-target system+user prompt, calls the
// Provider, strips markdown fences, and validates per target. On a repairable
// validation failure it repairs exactly once (at most two Provider.Complete
// calls total), feeding the exact validation error back into a repair prompt.
// The terminal error for every target is ErrInvalidSQLGeneratedByAI.
//
// The provided context should handle overall timeout; this method applies an
// additional internal timeout (g.callTimeout) for the provider call(s).
func (g *Generator) GenerateQuery(ctx context.Context, in GenerateQueryInput) (string, error) {
	g.logger.Debug("generating query from natural language",
		"target", in.Target,
		"query_length", len(in.NaturalLanguageQuery),
		"schema_length", len(in.Schema),
		"table", in.TableName,
		"current_query_length", len(in.CurrentQuery),
		"provider", g.provider.Name(),
		"model", g.model,
		"max_tokens", g.maxTokens,
		"temperature", g.temperature,
		"call_timeout", g.callTimeout,
	)

	now := time.Now()
	systemPrompt := systemPromptFor(in.Target, in.TableName, in.Schema)
	userPrompt := userPromptFor(in.Target, in.NaturalLanguageQuery, in.CurrentQuery, now)

	// Attempt 1. completeAndValidate applies its OWN g.callTimeout window per
	// call (derived from ctx), so a slow first attempt can't starve the repair.
	validated, cleaned, validationErr, err := g.completeAndValidate(ctx, in.Target, systemPrompt, userPrompt)
	if err != nil {
		return "", err
	}
	if validationErr == nil {
		g.logger.Debug("successfully generated and validated query", "target", in.Target, "query_length", len(validated))
		return validated, nil
	}

	g.logger.Warn("AI generated invalid query on first attempt", "target", in.Target, "error", validationErr)

	// Repair loop, capped at exactly ONE repair attempt (max 2 Complete calls).
	// LogsQL is not repairable: there is no local LogsQL validator to repair
	// against, so a repair prompt would have nothing meaningful to correct.
	if !isRepairableTarget(in.Target) {
		return "", ErrInvalidSQLGeneratedByAI
	}

	repairPrompt := repairPromptFor(in.Target, userPrompt, cleaned, validationErr)
	validated, _, validationErr, err = g.completeAndValidate(ctx, in.Target, systemPrompt, repairPrompt)
	if err != nil {
		return "", err
	}
	if validationErr == nil {
		g.logger.Debug("AI query repaired successfully", "target", in.Target, "query_length", len(validated))
		return validated, nil
	}

	g.logger.Error("AI generated invalid query after repair", "target", in.Target, "error", validationErr)
	return "", ErrInvalidSQLGeneratedByAI
}

// completeAndValidate performs one provider completion, strips markdown fences,
// and validates the result for the target. transportErr is the provider/network
// error (non-nil means the call itself failed); validationErr is a per-target
// validation failure (wrapping ErrInvalidSQLGeneratedByAI). cleaned is the
// markdown-stripped output, used to build a repair prompt.
func (g *Generator) completeAndValidate(ctx context.Context, target TargetLanguage, system, user string) (validated, cleaned string, validationErr, transportErr error) {
	// Each provider call gets its own timeout window so retries (the repair
	// attempt) are not starved by a slow first attempt sharing one deadline.
	callCtx, cancel := context.WithTimeout(ctx, g.callTimeout)
	defer cancel()

	raw, err := g.provider.Complete(callCtx, CompletionRequest{
		System:      system,
		User:        user,
		Model:       g.model,
		MaxTokens:   g.maxTokens,
		Temperature: g.temperature,
	})
	if err != nil {
		g.logger.Error("error calling AI provider", "provider", g.provider.Name(), "error", err)
		return "", "", nil, err
	}

	cleaned = removeMarkdownFences(raw)
	validated, validationErr = validateForTarget(target, cleaned)
	if validationErr != nil {
		g.logger.Debug("AI query failed validation", "target", target, "query_text", cleaned, "error", validationErr)
	}
	return validated, cleaned, validationErr, nil
}

// targetLanguageName returns the human-facing language name used in prompts.
func targetLanguageName(target TargetLanguage) string {
	switch target {
	case TargetLogchefQL:
		return "LogchefQL"
	case TargetLogsQL:
		return "LogsQL"
	default:
		return "ClickHouse SQL"
	}
}

// systemPromptFor builds the target-specific system prompt. The ClickHouse-SQL
// prompt is byte-identical to the pre-P2 client.
func systemPromptFor(target TargetLanguage, tableName, schema string) string {
	switch target {
	case TargetLogchefQL:
		return fmt.Sprintf(LogchefQLSystemPromptFormat, schema)
	case TargetLogsQL:
		return fmt.Sprintf(LogsQLSystemPromptFormat, schema)
	default:
		return fmt.Sprintf(DefaultSystemPromptTableFormat, tableName, schema)
	}
}

// userPromptFor builds the target-specific user prompt. The ClickHouse-SQL
// wording is reproduced exactly to keep that target byte-identical to pre-P2.
func userPromptFor(target TargetLanguage, naturalLanguageQuery, currentQuery string, now time.Time) string {
	if target == TargetClickHouseSQL {
		if currentQuery != "" && strings.TrimSpace(currentQuery) != "" {
			return fmt.Sprintf("Generate a ClickHouse SQL query to answer this question: %s. The current time is %s.\n\nFor context, here is the user's current query:\n%s\n\nPlease use this current query as a reference and modify it as needed to answer the user's question.",
				naturalLanguageQuery, now.Format(time.RFC3339), currentQuery)
		}
		return fmt.Sprintf("Generate a ClickHouse SQL query to answer this question: %s. The current time is %s.",
			naturalLanguageQuery, now.Format(time.RFC3339))
	}

	langName := targetLanguageName(target)
	if currentQuery != "" && strings.TrimSpace(currentQuery) != "" {
		return fmt.Sprintf("Generate a %s query to answer this question: %s. The current time is %s.\n\nFor context, here is the user's current query:\n%s\n\nPlease use this current query as a reference and modify it as needed to answer the user's question.",
			langName, naturalLanguageQuery, now.Format(time.RFC3339), currentQuery)
	}
	return fmt.Sprintf("Generate a %s query to answer this question: %s. The current time is %s.",
		langName, naturalLanguageQuery, now.Format(time.RFC3339))
}

// repairPromptFor builds a repair user prompt from the original ask, the invalid
// output, and the exact validation error.
func repairPromptFor(target TargetLanguage, originalUserPrompt, invalidOutput string, validationErr error) string {
	langName := targetLanguageName(target)
	return fmt.Sprintf("%s\n\nYour previous %s output was invalid and could not be used:\n%s\n\nThe validation error was: %s\n\nRegenerate a corrected %s query. Output ONLY the query with no explanation and no code fences.",
		originalUserPrompt, langName, invalidOutput, validationErr.Error(), langName)
}

// validateForTarget validates a markdown-stripped query for its target and, for
// ClickHouse SQL, returns the reformatted query. For other targets it returns
// the input unchanged when valid.
func validateForTarget(target TargetLanguage, cleaned string) (string, error) {
	switch target {
	case TargetLogchefQL:
		if strings.TrimSpace(cleaned) == "" {
			return "", ErrInvalidSQLGeneratedByAI
		}
		res := logchefql.Validate(cleaned)
		if !res.Valid {
			msg := "invalid LogchefQL syntax"
			if res.Error != nil {
				msg = res.Error.Error()
			}
			return "", fmt.Errorf("%w: %s", ErrInvalidSQLGeneratedByAI, msg)
		}
		return cleaned, nil
	case TargetLogsQL:
		// No local LogsQL parser exists in the codebase, and we deliberately do
		// NOT fabricate one. Best-effort validation only: reject an empty
		// (post-strip) response and otherwise accept as-is. Because there is
		// nothing to validate the query against, LogsQL is NOT repairable.
		if strings.TrimSpace(cleaned) == "" {
			return "", ErrInvalidSQLGeneratedByAI
		}
		return cleaned, nil
	default: // TargetClickHouseSQL
		if strings.TrimSpace(cleaned) == "" {
			return "", ErrInvalidSQLGeneratedByAI
		}
		return validateAndFormatSQL(cleaned)
	}
}

// isRepairableTarget reports whether a failed generation for the target can be
// repaired (i.e. there is a validator whose error we can feed back). ClickHouse
// SQL and LogchefQL are repairable; LogsQL is not.
func isRepairableTarget(target TargetLanguage) bool {
	return target == TargetClickHouseSQL || target == TargetLogchefQL
}

// removeMarkdownFences strips markdown code fences (```sql ... ``` or ``` ... ```)
// and any surrounding whitespace from the AI's raw output.
func removeMarkdownFences(rawResponse string) string {
	matches := codeBlockRegex.FindStringSubmatch(rawResponse)
	var sql string
	if len(matches) > 1 {
		// Extract the content from within the code block
		sql = matches[1]
	} else {
		// No code blocks found, so just remove any backtick markers if present
		sql = strings.ReplaceAll(rawResponse, "```sql", "") // Order matters: ```sql before ```
		sql = strings.ReplaceAll(sql, "```", "")
	}
	return strings.TrimSpace(sql)
}

// validateAndFormatSQL tries to parse the given SQL string using a ClickHouse parser.
// If parsing is successful, it returns the formatted SQL.
// If parsing fails, or the resulting SQL is empty, it returns ErrInvalidSQLGeneratedByAI.
func validateAndFormatSQL(sqlInput string) (string, error) {
	if strings.TrimSpace(sqlInput) == "" {
		return "", ErrInvalidSQLGeneratedByAI // Empty input is invalid
	}

	// Handle escaped single quotes ('') which the parser might misinterpret
	const placeholder = "___ESCAPED_QUOTE___"
	processedSQL := strings.ReplaceAll(sqlInput, "''", placeholder)

	parser := clickhouseparser.NewParser(processedSQL)
	stmts, err := parser.ParseStmts()

	if err != nil {
		// Parsing failed
		return "", fmt.Errorf("%w: %v", ErrInvalidSQLGeneratedByAI, err)
	}

	if len(stmts) == 0 {
		// Parsing succeeded but no statements were found
		return "", ErrInvalidSQLGeneratedByAI
	}

	// Render the parsed statement back to SQL via the parser's Formatter
	// (clickhouse-sql-parser v0.5 replaced node.String() with this).
	f := clickhouseparser.NewFormatter()
	f.WriteExpr(stmts[0])
	formattedSQL := f.String()
	// Restore escaped quotes
	formattedSQL = strings.ReplaceAll(formattedSQL, placeholder, "''")
	formattedSQL = strings.TrimSpace(formattedSQL) // Ensure formatted SQL isn't just whitespace

	// Validate that we have a non-empty SQL query after formatting
	if formattedSQL == "" {
		return "", ErrInvalidSQLGeneratedByAI
	}

	return formattedSQL, nil
}
